import sublime, sublime_plugin
import re
def match(rex, str):
    m = rex.match(str)
    if m:
        return m.group(0)
    else:
        return None
class ModifierCompletions(sublime_plugin.EventListener):
    def on_query_completions(self, view, prefix, locations):
        # Only trigger within HTML
        # if not view.match_selector(locations[0],
        #         "text.html - source"):
        #     return []
        pt = locations[0] - len(prefix) - 1
        ch = view.substr(sublime.Region(pt, pt + 1))
        if ch != ' ':
            return []
        return ([
            ("action=\"url\"\tMT[M]", "action=\"${1:url}\""),
            ("append=\"1\"\tMT[M]", "append=\"${1:1}\""),
            ("author=\"author_foo\"\tMT[M]", "author=\"${1:author_foo}\""),
            ("author=\"author_user_name\"\tMT[M]", "author=\"${1:author_user_name}\""),
            ("authors=\"author_user_name\"\tMT[M]", "authors=\"${1:author_user_name}\""),
            ("author_id=\"id\"\tMT[M]", "author_id=\"${1:id}\""),
            ("author_ids=\"author_id\"\tMT[M]", "author_ids=\"${1:author_id}\""),
            ("blog_id=\"id\"\tMT[M]", "blog_id=\"${1:id}\""),
            ("blog_ids=\"all\"\tMT[M]", "blog_ids=\"${1:all}\""),
            ("blog_ids=\"children\"\tMT[M]", "blog_ids=\"${1:children}\""),
            ("blog_ids=\"ID\"\tMT[M]", "blog_ids=\"${1:ID}\""),
            ("blog_ids=\"siblings\"\tMT[M]", "blog_ids=\"${1:siblings}\""),
            ("by=\"action\"\tMT[M]", "by=\"${1:action}\""),
            ("by=\"date\"\tMT[M]", "by=\"${1:date}\""),
            ("by=\"service\"\tMT[M]", "by=\"${1:service}\""),
            ("by=\"stream\"\tMT[M]", "by=\"${1:stream}\""),
            ("by_blog=\"1\"\tMT[M]", "by_blog=\"${1:1}\""),
            ("by_user=\"1\"\tMT[M]", "by_user=\"${1:1}\""),
            ("cache=\"1\"\tMT[M]", "cache=\"${1:1}\""),
            ("cache_key=\"cache_key\"\tMT[M]", "cache_key=\"${1:cache_key}\""),
            ("cache_prefix=\"key_foo\"\tMT[M]", "cache_prefix=\"${1:key_foo}\""),
            ("capitalize=\"1\"\tMT[M]", "capitalize=\"1\""),
            ("cat=\"\"\tMT[M]", "cat=\"${1}\""),
            ("count_characters=\"1\"\tMT[M]", "count_characters=\"1\""),
            ("count_paragraphs=\"1\"\tMT[M]", "count_paragraphs=\"1\""),
            ("count_words=\"\"\tMT[M]", "count_words=\"${1}\""),
            ("days=\"N\"\tMT[M]", "days=\"${1:N}\""),
            ("decode_html=\"1\"\tMT[M]", "decode_html=\"1\""),
            ("decode_xml=\"1\"\tMT[M]", "decode_xml=\"1\""),
            ("direction=\"ascend\"\tMT[M]", "direction=\"${1:ascend}\""),
            ("direction=\"descend\"\tMT[M]", "direction=\"${1:descend}\""),
            ("dirify=\"1\"\tMT[M]", "dirify=\"1\""),
            ("display_name=\"display_name\"\tMT[M]", "display_name=\"${1:display_name}\""),
            ("display_names=\"display_name\"\tMT[M]", "display_names=\"${1:display_name}\""),
            ("element_id=\"id\"\tMT[M]", "element_id=\"${1:id}\""),
            ("encode_js=\"1\"\tMT[M]", "encode_js=\"1\""),
            ("encode_php=\"1\"\tMT[M]", "encode_php=\"1\""),
            ("encode_sha1=\"1\"\tMT[M]", "encode_sha1=\"1\""),
            ("encode_url=\"1\"\tMT[M]", "encode_url=\"1\""),
            ("encode_xml=\"1\"\tMT[M]", "encode_xml=\"1\""),
            ("enctype=\"enctype_foo\"\tMT[M]", "enctype=\"${1:enctype_foo}\""),
            ("escape=\"html\"\tMT[M]", "escape=\"html\""),
            ("escape=\"javascript\"\tMT[M]", "escape=\"javascript\""),
            ("escape=\"mail\"\tMT[M]", "escape=\"mail\""),
            ("escape=\"url\"\tMT[M]", "escape=\"url\""),
            ("exclude_blogs=\"ID\"\tMT[M]", "exclude_blogs=\"${1:ID}\""),
            ("field:customfieldbasename=\"foo\"\tMT[M]", "field:customfieldbasename=\"${1:foo}\""),
            ("filters=\"\"\tMT[M]", "filters=\"${1}\""),
            ("flavor=\"html\"\tMT[M]", "flavor=\"${1:html}\""),
            ("flavor=\"html/css\"\tMT[M]", "flavor=\"${1:html/css}\""),
            ("flavor=\"xhtml1\"\tMT[M]", "flavor=\"${1:xhtml1}\""),
            ("flavor=\"xhtml2\"\tMT[M]", "flavor=\"${1:xhtml2}\""),
            ("folder=\"folder_foo\"\tMT[M]", "folder=\"${1:folder_foo}\""),
            ("format=\"format\"\tMT[M]", "format=\"${1:format}\""),
            ("format_name=\"format_name\"\tMT[M]", "format_name=\"${1:format_name}\""),
            ("global=\"1\"\tMT[M]", "global=\"${1:1}\""),
            ("glue=\"foo\"\tMT[M]", "glue=\"${1:foo}\""),
            ("head_offset=\"N\"\tMT[M]", "head_offset=\"${1:N}\""),
            ("highlightingsearchword=\"\"\tDynamicMTML[M]", "highlightingsearchword=\"${1}\""),
            ("html_tag=\"element_foo\"\tMT[M]", "html_tag=\"${1:element_foo}\""),
            ("id=\"id\"\tMT[M]", "id=\"${1:id}\""),
            ("identifier=\"index_template_identifier\"\tMT[M]", "identifier=\"${1:index_template_identifier}\""),
            ("include_blogs=\"all\"\tMT[M]", "include_blogs=\"${1:all}\""),
            ("include_blogs=\"children\"\tMT[M]", "include_blogs=\"${1:children}\""),
            ("include_blogs=\"ID\"\tMT[M]", "include_blogs=\"${1:ID}\""),
            ("include_blogs=\"siblings\"\tMT[M]", "include_blogs=\"${1:siblings}\""),
            ("include_subfolders=\"1\"\tMT[M]", "include_subfolders=\"${1:1}\""),
            ("include_with_website=\"1\"\tMT[M]", "include_with_website=\"${1:1}\""),
            ("indent=\"1\"\tMT[M]", "indent=\"1\""),
            ("intval=\"\"\tDynamicMTML[M]", "intval=\"${1}\""),
            ("key=\"cache_key\"\tMT[M]", "key=\"${1:cache_key}\""),
            ("lastn=\"N\"\tMT[M]", "lastn=\"${1:N}\""),
            ("limit=\"N\"\tMT[M]", "limit=\"${1:N}\""),
            ("lower_case=\"1\"\tMT[M]", "lower_case=\"1\""),
            ("ltrim=\"1\"\tMT[M]", "ltrim=\"1\""),
            ("make_seo_basename=\"\"\tDynamicMTML[M]", "make_seo_basename=\"${1}\""),
            ("method=\"get\"\tMT[M]", "method=\"${1:get}\""),
            ("method=\"post\"\tMT[M]", "method=\"${1:post}\""),
            ("mteval=\"1\"\tMT[M]", "mteval=\"1\""),
            ("name=\"foo\"\tMT[M]", "name=\"${1:foo}\""),
            ("namespace=\"foo\"\tMT[M]", "namespace=\"${1:foo}\""),
            ("nl2br=\"xhtml\"\tMT[M]", "nl2br=\"${1:xhtml}\""),
            ("nofollowfy=\"1\"\tMT[M]", "nofollowfy=\"1\""),
            ("none=\"text\"\tMT[M]", "none=\"${1:text}\""),
            ("no_folder=\"1\"\tMT[M]", "no_folder=\"${1:1}\""),
            ("numify=\"1\"\tMT[M]", "numify=\"1\""),
            ("object_ds=\"\"\tMT[M]", "object_ds=\"${1:}\""),
            ("object_id=\"id\"\tMT[M]", "object_id=\"${1:id}\""),
            ("object_type=\"foo\"\tMT[M]", "object_type=\"${1:foo}\""),
            ("offset=\"N\"\tMT[M]", "offset=\"${1:N}\""),
            ("parent=\"1\"\tMT[M]", "parent=\"${1:1}\""),
            ("period=\"Sec\"\tMT[M]", "period=\"${1:Sec}\""),
            ("plural=\"text\"\tMT[M]", "plural=\"${1:text}\""),
            ("prepend=\"1\"\tMT[M]", "prepend=\"${1:1}\""),
            ("preserve_spaces=\"1\"\tMT[M]", "preserve_spaces=\"${1:1}\""),
            ("range_incl=\"\"\tMT[M]", "range_incl=\"${1:}\""),
            ("recently_commented_on=\"N\"\tMT[M]", "recently_commented_on=\"${1:N}\""),
            ("regex_replace=\"\"\tMT[M]", "regex_replace=\"${1}\""),
            ("regex_replace=\"//\",\"\"\tMT[M]", "regex_replace=\"/${1:RegExp}/\",\"${2:Replacement}\""),
            ("remove_html=\"1\"\tMT[M]", "remove_html=\"1\""),
            ("replace=\"\"\tMT[M]", "replace=\"${1}\""),
            ("rtrim=\"1\"\tMT[M]", "rtrim=\"1\""),
            ("sanitize=\"1\"\tMT[M]", "sanitize=\"${1:1}\""),
            ("script=\"function_foo\"\tMT[M]", "script=\"${1:function_foo}\""),
            ("service=\"service_id\"\tMT[M]", "service=\"${1:service_id}\""),
            ("setvar=\"\"\tMT[M]", "setvar=\"${1}\""),
            ("singular=\"text\"\tMT[M]", "singular=\"${1:text}\""),
            ("smarty_pants=\"1\"\tMT[M]", "smarty_pants=\"1\""),
            ("smart_dashes=\"1\"\tMT[M]", "smart_dashes=\"1\""),
            ("smart_ellipses=\"1\"\tMT[M]", "smart_ellipses=\"1\""),
            ("smart_quotes=\"1\"\tMT[M]", "smart_quotes=\"1\""),
            ("sort=\"authored_on\"\tMT[M]", "sort=\"${1:authored_on}\""),
            ("sort=\"created_on\"\tMT[M]", "sort=\"${1:created_on}\""),
            ("sort_by=\"author_id\"\tMT[M]", "sort_by=\"${1:author_id}\""),
            ("sort_by=\"created_on\"\tMT[M]", "sort_by=\"${1:created_on}\""),
            ("sort_by=\"excerpt\"\tMT[M]", "sort_by=\"${1:excerpt}\""),
            ("sort_by=\"foo\"\tMT[M]", "sort_by=\"${1:foo}\""),
            ("sort_by=\"modified_on\"\tMT[M]", "sort_by=\"${1:modified_on}\""),
            ("sort_by=\"status\"\tMT[M]", "sort_by=\"${1:status}\""),
            ("sort_by=\"title\"\tMT[M]", "sort_by=\"${1:title}\""),
            ("sort_order=\"ascend\"\tMT[M]", "sort_order=\"${1:ascend}\""),
            ("sort_order=\"descend\"\tMT[M]", "sort_order=\"${1:descend}\""),
            ("space_pad=\"N\"\tMT[M]", "space_pad=\"${1:N}\""),
            ("spacify=\"\"\tMT[M]", "spacify=\"${1}\""),
            ("spam_protect=\"1\"\tMT[M]", "spam_protect=\"1\""),
            ("sprintf=\"\"\tMT[M]", "sprintf=\"${1}\""),
            ("square=\"1\"\tMT[M]", "square=\"${1:1}\""),
            ("ssi=\"1\"\tMT[M]", "ssi=\"${1:1}\""),
            ("stream=\"stream_name\"\tMT[M]", "stream=\"${1:stream_name}\""),
            ("string_format=\"\"\tMT[M]", "string_format=\"${1}\""),
            ("strip=\"\"\tMT[M]", "strip=\"${1}\""),
            ("strip_linefeeds=\"1\"\tMT[M]", "strip_linefeeds=\"1\""),
            ("strip_tags=\"1\"\tMT[M]", "strip_tags=\"1\""),
            ("tag=\"tag_foo\"\tMT[M]", "tag=\"${1:tag_foo}\""),
            ("tags=\"tag_foo\"\tMT[M]", "tags=\"${1:tag_foo}\""),
            ("trim=\"1\"\tMT[M]", "trim=\"1\""),
            ("trimwhitespace=\"\"\tDynamicMTML[M]", "trimwhitespace=\"${1}\""),
            ("trim_spaces=\"1\"\tMT[M]", "trim_spaces=\"${1:1}\""),
            ("trim_to=\"N\"\tMT[M]", "trim_to=\"${1:N}\""),
            ("trim_to=\"N+\"\tMT[M]", "trim_to=\"${1:N}+${2}\""),
            ("type=\"\"\tMT[M]", "type=\"${1:}\""),
            ("unique=\"1\"\tMT[M]", "unique=\"${1:1}\""),
            ("upper_case=\"1\"\tMT[M]", "upper_case=\"1\""),
            ("utc=\"1\"\tMT[M]", "utc=\"${1:1}\""),
            ("value=\"\"\tMT[M]", "value=\"${1:}\""),
            ("var=\"variable_foo\"\tMT[M]", "var=\"${1:variable_foo}\""),
            ("variable_foo=\"value\"\tMT[M]", "variable_foo=\"${1:value}\""),
            ("wrap_text=\"N\"\tMT[M]", "wrap_text=\"${1:N}\""),
            ("zero_pad=\"N\"\tMT[M]", "zero_pad=\"${1:N}\""),
            ("__counter__\tMT[M]", "__counter__"),
            ("__even__\tMT[M]", "__even__"),
            ("__first__\tMT[M]", "__first__"),
            ("__last__\tMT[M]", "__last__"),
            ("__odd__\tMT[M]", "__odd__")
        ], sublime.INHIBIT_WORD_COMPLETIONS | sublime.INHIBIT_EXPLICIT_COMPLETIONS)
class MTTagCompletions(sublime_plugin.EventListener):
    def on_query_completions(self, view, prefix, locations):
        # Only trigger within HTML
        # if not view.match_selector(locations[0],
        #         "text.html - source"):
        #     return []
        pt = locations[0] - len(prefix) - 1
        ch = view.substr(sublime.Region(pt, pt + 1))
        if ch != '<':
            return []
        return ([
            # Block Tag
            ("mt:Actions\tMT[B]", "mt:Actions${1}>${2:Contents}</mt:Actions>"),
            ("mt:ActionsComment\tMT[B]", "mt:ActionsComment${1}>${2:Contents}</mt:ActionsComment>"),
            ("mt:ActionsEntry\tMT[B]", "mt:ActionsEntry${1}>${2:Contents}</mt:ActionsEntry>"),
            ("mt:ActionsFavorite\tMT[B]", "mt:ActionsFavorite${1}>${2:Contents}</mt:ActionsFavorite>"),
            ("mt:ActionsFooter\tMT[B]", "mt:ActionsFooter${1}>${2:Contents}</mt:ActionsFooter>"),
            ("mt:ActionsHeader\tMT[B]", "mt:ActionsHeader${1}>${2:Contents}</mt:ActionsHeader>"),
            ("mt:ActionStreams\tMT[B]", "mt:ActionStreams${1}>${2:Contents}</mt:ActionStreams>"),
            ("mt:ArchiveList\tMT[B]", "mt:ArchiveList${1}>${2:Contents}</mt:ArchiveList>"),
            ("mt:ArchiveListFooter\tMT[B]", "mt:ArchiveListFooter${1}>${2:Contents}</mt:ArchiveListFooter>"),
            ("mt:ArchiveListHeader\tMT[B]", "mt:ArchiveListHeader${1}>${2:Contents}</mt:ArchiveListHeader>"),
            ("mt:ArchiveNext\tMT[B]", "mt:ArchiveNext${1}>${2:Contents}</mt:ArchiveNext>"),
            ("mt:ArchivePrevious\tMT[B]", "mt:ArchivePrevious${1}>${2:Contents}</mt:ArchivePrevious>"),
            ("mt:Archives\tMT[B]", "mt:Archives${1}>${2:Contents}</mt:Archives>"),
            ("mt:Asset\tMT[B]", "mt:Asset${1}>${2:Contents}</mt:Asset>"),
            ("mt:AssetIsFirstInRow\tMT[B]", "mt:AssetIsFirstInRow${1}>${2:Contents}</mt:AssetIsFirstInRow>"),
            ("mt:AssetIsLastInRow\tMT[B]", "mt:AssetIsLastInRow${1}>${2:Contents}</mt:AssetIsLastInRow>"),
            ("mt:Assets\tMT[B]", "mt:Assets${1}>${2:Contents}</mt:Assets>"),
            ("mt:AssetsFooter\tMT[B]", "mt:AssetsFooter${1}>${2:Contents}</mt:AssetsFooter>"),
            ("mt:AssetsHeader\tMT[B]", "mt:AssetsHeader${1}>${2:Contents}</mt:AssetsHeader>"),
            ("mt:AssetTags\tMT[B]", "mt:AssetTags${1}>${2:Contents}</mt:AssetTags>"),
            ("mt:AudioCustomFields\tMT[B]", "mt:AudioCustomFields${1}>${2:Contents}</mt:AudioCustomFields>"),
            ("mt:AuthorCommentResponses\tMT[B]", "mt:AuthorCommentResponses${1}>${2:Contents}</mt:AuthorCommentResponses>"),
            ("mt:AuthorComments\tMT[B]", "mt:AuthorComments${1}>${2:Contents}</mt:AuthorComments>"),
            ("mt:AuthorCustomFields\tMT[B]", "mt:AuthorCustomFields${1}>${2:Contents}</mt:AuthorCustomFields>"),
            ("mt:AuthorFollowers\tMT[B]", "mt:AuthorFollowers${1}>${2:Contents}</mt:AuthorFollowers>"),
            ("mt:AuthorFollowing\tMT[B]", "mt:AuthorFollowing${1}>${2:Contents}</mt:AuthorFollowing>"),
            ("mt:AuthorFollowingComments\tMT[B]", "mt:AuthorFollowingComments${1}>${2:Contents}</mt:AuthorFollowingComments>"),
            ("mt:AuthorFollowingEntries\tMT[B]", "mt:AuthorFollowingEntries${1}>${2:Contents}</mt:AuthorFollowingEntries>"),
            ("mt:AuthorFollowingFavorites\tMT[B]", "mt:AuthorFollowingFavorites${1}>${2:Contents}</mt:AuthorFollowingFavorites>"),
            ("mt:AuthorHasEntry\tMT[B]", "mt:AuthorHasEntry${1}>${2:Contents}</mt:AuthorHasEntry>"),
            ("mt:AuthorHasPage\tMT[B]", "mt:AuthorHasPage${1}>${2:Contents}</mt:AuthorHasPage>"),
            ("mt:AuthorNext\tMT[B]", "mt:AuthorNext${1}>${2:Contents}</mt:AuthorNext>"),
            ("mt:AuthorPrevious\tMT[B]", "mt:AuthorPrevious${1}>${2:Contents}</mt:AuthorPrevious>"),
            ("mt:Authors\tMT[B]", "mt:Authors${1}>${2:Contents}</mt:Authors>"),
            ("mt:AuthorUserpicAsset\tMT[B]", "mt:AuthorUserpicAsset${1}>${2:Contents}</mt:AuthorUserpicAsset>"),
            ("mt:BlogCustomFields\tMT[B]", "mt:BlogCustomFields${1}>${2:Contents}</mt:BlogCustomFields>"),
            ("mt:BlogParentWebsite\tMT[B]", "mt:BlogParentWebsite${1}>${2:Contents}</mt:BlogParentWebsite>"),
            ("mt:BlogResultFooter\tMT[B]", "mt:BlogResultFooter${1}>${2:Contents}</mt:BlogResultFooter>"),
            ("mt:BlogResultHeader\tMT[B]", "mt:BlogResultHeader${1}>${2:Contents}</mt:BlogResultHeader>"),
            ("mt:Blogs\tMT[B]", "mt:Blogs${1}>${2:Contents}</mt:Blogs>"),
            ("mt:BuildRecurs\tDynamicMTML[B]", "mt:BuildRecurs${1}>${2}</mt:BuildRecurs>"),
            ("mt:Calendar\tMT[B]", "mt:Calendar${1}>${2:Contents}</mt:Calendar>"),
            ("mt:CalendarWeekFooter\tMT[B]", "mt:CalendarWeekFooter${1}>${2:Contents}</mt:CalendarWeekFooter>"),
            ("mt:CalendarWeekHeader\tMT[B]", "mt:CalendarWeekHeader${1}>${2:Contents}</mt:CalendarWeekHeader>"),
            ("mt:Categories\tMT[B]", "mt:Categories${1}>${2:Contents}</mt:Categories>"),
            ("mt:CategoryCustomFields\tMT[B]", "mt:CategoryCustomFields${1}>${2:Contents}</mt:CategoryCustomFields>"),
            ("mt:CategoryNext\tMT[B]", "mt:CategoryNext${1}>${2:Contents}</mt:CategoryNext>"),
            ("mt:CategoryPrevious\tMT[B]", "mt:CategoryPrevious${1}>${2:Contents}</mt:CategoryPrevious>"),
            ("mt:ClientAuthorBlock\tDynamicMTML[B]", "mt:ClientAuthorBlock${1}>${2}</mt:ClientAuthorBlock>"),
            ("mt:CommentCustomFields\tMT[B]", "mt:CommentCustomFields${1}>${2:Contents}</mt:CommentCustomFields>"),
            ("mt:CommentEntry\tMT[B]", "mt:CommentEntry${1}>${2:Contents}</mt:CommentEntry>"),
            ("mt:CommenterUserpicAsset\tMT[B]", "mt:CommenterUserpicAsset${1}>${2:Contents}</mt:CommenterUserpicAsset>"),
            ("mt:CommentOut\tDynamicMTML[B]", "mt:CommentOut${1}>${2}</mt:CommentOut>"),
            ("mt:CommentParent\tMT[B]", "mt:CommentParent${1}>${2:Contents}</mt:CommentParent>"),
            ("mt:CommentReplies\tMT[B]", "mt:CommentReplies${1}>${2:Contents}</mt:CommentReplies>"),
            ("mt:Comments\tMT[B]", "mt:Comments${1}>${2:Contents}</mt:Comments>"),
            ("mt:CommentsFooter\tMT[B]", "mt:CommentsFooter${1}>${2:Contents}</mt:CommentsFooter>"),
            ("mt:CommentsHeader\tMT[B]", "mt:CommentsHeader${1}>${2:Contents}</mt:CommentsHeader>"),
            ("mt:CommentStrip\tDynamicMTML[B]", "mt:CommentStrip${1}>${2}</mt:CommentStrip>"),
            ("mt:CustomFieldIsRequired\tMT[B]", "mt:CustomFieldIsRequired${1}>${2:Contents}</mt:CustomFieldIsRequired>"),
            ("mt:DateFooter\tMT[B]", "mt:DateFooter${1}>${2:Contents}</mt:DateFooter>"),
            ("mt:DateHeader\tMT[B]", "mt:DateHeader${1}>${2:Contents}</mt:DateHeader>"),
            ("mt:DynamicMTML\tDynamicMTML[B]", "mt:DynamicMTML>${1}</mt:DynamicMTML>"),
            ("mt:Else\tMT[B]", "mt:Else${1}>${2:Contents}</mt:Else>"),
            ("mt:Entries\tMT[B]", "mt:Entries${1}>${2:Contents}</mt:Entries>"),
            ("mt:EntriesFooter\tMT[B]", "mt:EntriesFooter${1}>${2:Contents}</mt:EntriesFooter>"),
            ("mt:EntriesHeader\tMT[B]", "mt:EntriesHeader${1}>${2:Contents}</mt:EntriesHeader>"),
            ("mt:EntriesWithSubCategories\tMT[B]", "mt:EntriesWithSubCategories${1}>${2:Contents}</mt:EntriesWithSubCategories>"),
            ("mt:EntryAdditionalCategories\tMT[B]", "mt:EntryAdditionalCategories${1}>${2:Contents}</mt:EntryAdditionalCategories>"),
            ("mt:EntryAssets\tMT[B]", "mt:EntryAssets${1}>${2:Contents}</mt:EntryAssets>"),
            ("mt:EntryAuthorUserpicAsset\tMT[B]", "mt:EntryAuthorUserpicAsset${1}>${2:Contents}</mt:EntryAuthorUserpicAsset>"),
            ("mt:EntryCategories\tMT[B]", "mt:EntryCategories${1}>${2:Contents}</mt:EntryCategories>"),
            ("mt:EntryCategoryBlock\tDynamicMTML[B]", "mt:EntryCategoryBlock${1}>${2}</mt:EntryCategoryBlock>"),
            ("mt:EntryCustomFields\tMT[B]", "mt:EntryCustomFields${1}>${2:Contents}</mt:EntryCustomFields>"),
            ("mt:EntryNext\tMT[B]", "mt:EntryNext${1}>${2:Contents}</mt:EntryNext>"),
            ("mt:EntryPrevious\tMT[B]", "mt:EntryPrevious${1}>${2:Contents}</mt:EntryPrevious>"),
            ("mt:EntryPrimaryCategory\tMT[B]", "mt:EntryPrimaryCategory${1}>${2:Contents}</mt:EntryPrimaryCategory>"),
            ("mt:EntryTags\tMT[B]", "mt:EntryTags${1}>${2:Contents}</mt:EntryTags>"),
            ("mt:Feed\tMT[B]", "mt:Feed${1}>${2:Contents}</mt:Feed>"),
            ("mt:FeedEntries\tMT[B]", "mt:FeedEntries${1}>${2:Contents}</mt:FeedEntries>"),
            ("mt:FileCustomFields\tMT[B]", "mt:FileCustomFields${1}>${2:Contents}</mt:FileCustomFields>"),
            ("mt:FolderCustomFields\tMT[B]", "mt:FolderCustomFields${1}>${2:Contents}</mt:FolderCustomFields>"),
            ("mt:FolderFooter\tMT[B]", "mt:FolderFooter${1}>${2:Contents}</mt:FolderFooter>"),
            ("mt:FolderHeader\tMT[B]", "mt:FolderHeader${1}>${2:Contents}</mt:FolderHeader>"),
            ("mt:FolderNext\tMT[B]", "mt:FolderNext${1}>${2:Contents}</mt:FolderNext>"),
            ("mt:FolderPrevious\tMT[B]", "mt:FolderPrevious${1}>${2:Contents}</mt:FolderPrevious>"),
            ("mt:Folders\tMT[B]", "mt:Folders${1}>${2:Contents}</mt:Folders>"),
            ("mt:For\tMT[B]", "mt:For var=\"${1:i}\" from=\"${2}\" to=\"${3}\"${4: glue=\"\"}>${5:Contents}</mt:For>"),
            ("mt:HasNoParentCategory\tMT[B]", "mt:HasNoParentCategory${1}>${2:Contents}</mt:HasNoParentCategory>"),
            ("mt:HasNoSubCategories\tMT[B]", "mt:HasNoSubCategories${1}>${2:Contents}</mt:HasNoSubCategories>"),
            ("mt:HasParentCategory\tMT[B]", "mt:HasParentCategory${1}>${2:Contents}</mt:HasParentCategory>"),
            ("mt:HasParentFolder\tMT[B]", "mt:HasParentFolder${1}>${2:Contents}</mt:HasParentFolder>"),
            ("mt:HasSubCategories\tMT[B]", "mt:HasSubCategories${1}>${2:Contents}</mt:HasSubCategories>"),
            ("mt:HasSubFolders\tMT[B]", "mt:HasSubFolders${1}>${2:Contents}</mt:HasSubFolders>"),
            ("mt:Ignore\tMT[B]", "mt:Ignore>${1}</mt:Ignore>"),
            ("mt:ImageCustomFields\tMT[B]", "mt:ImageCustomFields${1}>${2:Contents}</mt:ImageCustomFields>"),
            ("mt:IncludeBlock\tMT[B]", "mt:IncludeBlock${1}>${2:Contents}</mt:IncludeBlock>"),
            ("mt:IndexList\tMT[B]", "mt:IndexList${1}>${2:Contents}</mt:IndexList>"),
            ("mt:LoginAuthorCtx\tDynamicMTML[B]", "mt:LoginAuthorCtx${1}>${2}</mt:LoginAuthorCtx>"),
            ("mt:Loop\tMT[B]", "mt:Loop name=\"${1:VariableName}\"${2: sort_by=\"\"}${3: glue=\"\"}>${4:Contents}</mt:Loop>"),
            ("mt:MarkdownOptions\tMT[B]", "mt:MarkdownOptions${1}>${2:Contents}</mt:MarkdownOptions>"),
            ("mt:MultiBlog\tMT[B]", "mt:MultiBlog${1}>${2:Contents}</mt:MultiBlog>"),
            ("mt:MultiBlogLocalBlog\tMT[B]", "mt:MultiBlogLocalBlog${1}>${2:Contents}</mt:MultiBlogLocalBlog>"),
            ("mt:NonDynamicMTML\tDynamicMTML[B]", "mt:NonDynamicMTML${1}>${2}</mt:NonDynamicMTML>"),
            ("mt:NoSearch\tMT[B]", "mt:NoSearch${1}>${2:Contents}</mt:NoSearch>"),
            ("mt:NoSearchResults\tMT[B]", "mt:NoSearchResults${1}>${2:Contents}</mt:NoSearchResults>"),
            ("mt:OtherBlog\tMT[B]", "mt:OtherBlog${1}>${2:Contents}</mt:OtherBlog>"),
            ("mt:OtherProfiles\tMT[B]", "mt:OtherProfiles${1}>${2:Contents}</mt:OtherProfiles>"),
            ("mt:PageAssets\tMT[B]", "mt:PageAssets${1}>${2:Contents}</mt:PageAssets>"),
            ("mt:PageCustomFields\tMT[B]", "mt:PageCustomFields${1}>${2:Contents}</mt:PageCustomFields>"),
            ("mt:PageFolder\tMT[B]", "mt:PageFolder${1}>${2:Contents}</mt:PageFolder>"),
            ("mt:PageNext\tMT[B]", "mt:PageNext${1}>${2:Contents}</mt:PageNext>"),
            ("mt:PagePrevious\tMT[B]", "mt:PagePrevious${1}>${2:Contents}</mt:PagePrevious>"),
            ("mt:PagerBlock\tMT[B]", "mt:PagerBlock${1}>${2:Contents}</mt:PagerBlock>"),
            ("mt:Pages\tMT[B]", "mt:Pages${1}>${2:Contents}</mt:Pages>"),
            ("mt:PagesFooter\tMT[B]", "mt:PagesFooter${1}>${2:Contents}</mt:PagesFooter>"),
            ("mt:PagesHeader\tMT[B]", "mt:PagesHeader${1}>${2:Contents}</mt:PagesHeader>"),
            ("mt:PageTags\tMT[B]", "mt:PageTags${1}>${2:Contents}</mt:PageTags>"),
            ("mt:ParentCategories\tMT[B]", "mt:ParentCategories${1}>${2:Contents}</mt:ParentCategories>"),
            ("mt:ParentCategory\tMT[B]", "mt:ParentCategory${1}>${2:Contents}</mt:ParentCategory>"),
            ("mt:ParentFolder\tMT[B]", "mt:ParentFolder${1}>${2:Contents}</mt:ParentFolder>"),
            ("mt:ParentFolders\tMT[B]", "mt:ParentFolders${1}>${2:Contents}</mt:ParentFolders>"),
            ("mt:PasswordValidation\tMT[B]", "mt:PasswordValidation${1}>${2:Contents}</mt:PasswordValidation>"),
            ("mt:PasswordValidationRule\tMT[B]", "mt:PasswordValidationRule${1}>${2:Contents}</mt:PasswordValidationRule>"),
            ("mt:PingEntry\tMT[B]", "mt:PingEntry${1}>${2:Contents}</mt:PingEntry>"),
            ("mt:Pings\tMT[B]", "mt:Pings${1}>${2:Contents}</mt:Pings>"),
            ("mt:PingsFooter\tMT[B]", "mt:PingsFooter${1}>${2:Contents}</mt:PingsFooter>"),
            ("mt:PingsHeader\tMT[B]", "mt:PingsHeader${1}>${2:Contents}</mt:PingsHeader>"),
            ("mt:PingsSent\tMT[B]", "mt:PingsSent${1}>${2:Contents}</mt:PingsSent>"),
            ("mt:ProfileServices\tMT[B]", "mt:ProfileServices${1}>${2:Contents}</mt:ProfileServices>"),
            ("mt:QueryLoop\tDynamicMTML[B]", "mt:QueryLoop${1}>${2}</mt:QueryLoop>"),
            ("mt:QueryVars\tDynamicMTML[B]", "mt:QueryVars${1}>${2}</mt:QueryVars>"),
            ("mt:RawMTML\tDynamicMTML[B]", "mt:RawMTML${1}>${2}</mt:RawMTML>"),
            ("mt:ReferralKeywords\tDynamicMTML[B]", "mt:ReferralKeywords${1}>${2}</mt:ReferralKeywords>"),
            ("mt:SearchEntries\tDynamicMTML[B]", "mt:SearchEntries${1}>${2}</mt:SearchEntries>"),
            ("mt:SearchResults\tMT[B]", "mt:SearchResults${1}>${2:Contents}</mt:SearchResults>"),
            ("mt:SearchResultsFooter\tMT[B]", "mt:SearchResultsFooter${1}>${2:Contents}</mt:SearchResultsFooter>"),
            ("mt:SearchResultsHeader\tMT[B]", "mt:SearchResultsHeader${1}>${2:Contents}</mt:SearchResultsHeader>"),
            ("mt:Section\tMT[B]", "mt:Section${1}>${2:Contents}</mt:Section>"),
            ("mt:SetHashVar\tMT[B]", "mt:SetHashVar${1}>${2:Contents}</mt:SetHashVar>"),
            ("mt:SetQueryVars\tDynamicMTML[B]", "mt:SetQueryVars${1}>${2}</mt:SetQueryVars>"),
            ("mt:SetVarBlock\tMT[B]", "mt:SetVarBlock name=\"${1:VariableName}\">${2:Contents}</mt:SetVarBlock>"),
            ("mt:SetVars\tMT[B]", "mt:SetVars>\n${1:Variable Name}=${2:Value}\n</mt:SetVars>"),
            ("mt:SetVarTemplate\tMT[B]", "mt:SetVarTemplate name=\"${1:Variable Name}\">${2:Contents}</mt:SetVarTemplate>"),
            ("mt:SplitVars\tDynamicMTML[B]", "mt:SplitVars${1}>${2}</mt:SplitVars>"),
            ("mt:StreamActionRollup\tMT[B]", "mt:StreamActionRollup${1}>${2:Contents}</mt:StreamActionRollup>"),
            ("mt:StreamActionTags\tMT[B]", "mt:StreamActionTags${1}>${2:Contents}</mt:StreamActionTags>"),
            ("mt:SubCategories\tMT[B]", "mt:SubCategories${1}>${2:Contents}</mt:SubCategories>"),
            ("mt:SubCatIsFirst\tMT[B]", "mt:SubCatIsFirst${1}>${2:Contents}</mt:SubCatIsFirst>"),
            ("mt:SubCatIsLast\tMT[B]", "mt:SubCatIsLast${1}>${2:Contents}</mt:SubCatIsLast>"),
            ("mt:SubFolders\tMT[B]", "mt:SubFolders${1}>${2:Contents}</mt:SubFolders>"),
            ("mt:Tags\tMT[B]", "mt:Tags${1}>${2:Contents}</mt:Tags>"),
            ("mt:TemplateCustomFields\tMT[B]", "mt:TemplateCustomFields${1}>${2:Contents}</mt:TemplateCustomFields>"),
            ("mt:Textile\tMT[B]", "mt:Textile${1}>${2:Contents}</mt:Textile>"),
            ("mt:TopLevelCategories\tMT[B]", "mt:TopLevelCategories${1}>${2:Contents}</mt:TopLevelCategories>"),
            ("mt:TopLevelFolder\tMT[B]", "mt:TopLevelFolder${1}>${2:Contents}</mt:TopLevelFolder>"),
            ("mt:TopLevelFolders\tMT[B]", "mt:TopLevelFolders${1}>${2:Contents}</mt:TopLevelFolders>"),
            ("mt:TopLevelParent\tMT[B]", "mt:TopLevelParent${1}>${2:Contents}</mt:TopLevelParent>"),
            ("mt:Unless\tMT[B]", "mt:Unless name=\"${1:VariableName}\">${2:Contents}</mt:Unless>"),
            ("mt:VideoCustomFields\tMT[B]", "mt:VideoCustomFields${1}>${2:Contents}</mt:VideoCustomFields>"),
            ("mt:WebsiteCustomFields\tMT[B]", "mt:WebsiteCustomFields${1}>${2:Contents}</mt:WebsiteCustomFields>"),
            ("mt:WebsiteHasBlog\tMT[B]", "mt:WebsiteHasBlog${1}>${2:Contents}</mt:WebsiteHasBlog>"),
            ("mt:Websites\tMT[B]", "mt:Websites${1}>${2:Contents}</mt:Websites>"),
            ("mtapp:Form\tMT[B]", "mtapp:Form${1}>${2:Contents}</mtapp:Form>"),
            ("mtapp:Listing\tMT[B]", "mtapp:Listing${1}>${2:Contents}</mtapp:Listing>"),
            ("mtapp:Setting\tMT[B]", "mtapp:Setting${1}>${2:Contents}</mtapp:Setting>"),
            ("mtapp:SettingGroup\tMT[B]", "mtapp:SettingGroup${1}>${2:Contents}</mtapp:SettingGroup>"),
            ("mtapp:StatusMsg\tMT[B]", "mtapp:StatusMsg${1}>${2:Contents}</mtapp:StatusMsg>"),
            ("mtapp:Widget\tMT[B]", "mtapp:Widget${1}>${2:Contents}</mtapp:Widget>"),
            # Conditional Tag
            ("mt:AssetIfTagged\tMT[C]", "mt:AssetIfTagged${1}>${2:Contents}</mt:AssetIfTagged>"),
            ("mt:AuthorIfFollowed\tMT[C]", "mt:AuthorIfFollowed${1}>${2:Contents}</mt:AuthorIfFollowed>"),
            ("mt:AuthorIfFollowing\tMT[C]", "mt:AuthorIfFollowing${1}>${2:Contents}</mt:AuthorIfFollowing>"),
            ("mt:BlogIfCCLicense\tMT[C]", "mt:BlogIfCCLicense${1}>${2:Contents}</mt:BlogIfCCLicense>"),
            ("mt:BlogIfCommentsOpen\tMT[C]", "mt:BlogIfCommentsOpen${1}>${2:Contents}</mt:BlogIfCommentsOpen>"),
            ("mt:CalendarIfBlank\tMT[C]", "mt:CalendarIfBlank${1}>${2:Contents}</mt:CalendarIfBlank>"),
            ("mt:CalendarIfEntries\tMT[C]", "mt:CalendarIfEntries${1}>${2:Contents}</mt:CalendarIfEntries>"),
            ("mt:CalendarIfNoEntries\tMT[C]", "mt:CalendarIfNoEntries${1}>${2:Contents}</mt:CalendarIfNoEntries>"),
            ("mt:CalendarIfToday\tMT[C]", "mt:CalendarIfToday${1}>${2:Contents}</mt:CalendarIfToday>"),
            ("mt:CategoryIfAllowPings\tMT[C]", "mt:CategoryIfAllowPings${1}>${2:Contents}</mt:CategoryIfAllowPings>"),
            ("mt:CommenterIfTrusted\tMT[C]", "mt:CommenterIfTrusted${1}>${2:Contents}</mt:CommenterIfTrusted>"),
            ("mt:CommentIfModerated\tMT[C]", "mt:CommentIfModerated${1}>${2:Contents}</mt:CommentIfModerated>"),
            ("mt:ElseIf\tMT[C]", "mt:ElseIf${1}>${2:Contents}</mt:ElseIf>"),
            ("mt:EntryIfAllowComments\tMT[C]", "mt:EntryIfAllowComments${1}>${2:Contents}</mt:EntryIfAllowComments>"),
            ("mt:EntryIfAllowPings\tMT[C]", "mt:EntryIfAllowPings${1}>${2:Contents}</mt:EntryIfAllowPings>"),
            ("mt:EntryIfCategory\tMT[C]", "mt:EntryIfCategory${1}>${2:Contents}</mt:EntryIfCategory>"),
            ("mt:EntryIfCommentsOpen\tMT[C]", "mt:EntryIfCommentsOpen${1}>${2:Contents}</mt:EntryIfCommentsOpen>"),
            ("mt:EntryIfExtended\tMT[C]", "mt:EntryIfExtended${1}>${2:Contents}</mt:EntryIfExtended>"),
            ("mt:EntryIfTagged\tMT[C]", "mt:EntryIfTagged${1}>${2:Contents}</mt:EntryIfTagged>"),
            ("mt:If\tMT[C]", "mt:If name=\"${1:VariableName}\">${2:Contents}</mt:If>"),
            ("mt:If else\tMT[C]", "mt:If name=\"${1:VarName}\">${2:True Contents}<mt:Else>${3:False Contents}</mt:If>"),
            ("mt:If tag\tMT[C]", "mt:If tag=\"${1:TagName}\">${2:Contents}</mt:If>"),
            ("mt:If tag else\tMT[C]", "mt:If tag=\"${1:TagName}\">${2:True Contents}<mt:Else>${3:False Contents}</mt:If>"),
            ("mt:IfAllowCommentHTML\tMT[C]", "mt:IfAllowCommentHTML${1}>${2:Contents}</mt:IfAllowCommentHTML>"),
            ("mt:IfAnonymousRecommendAllowed\tMT[C]", "mt:IfAnonymousRecommendAllowed${1}>${2:Contents}</mt:IfAnonymousRecommendAllowed>"),
            ("mt:IfArchiveType\tMT[C]", "mt:IfArchiveType${1}>${2:Contents}</mt:IfArchiveType>"),
            ("mt:IfArchiveTypeEnabled\tMT[C]", "mt:IfArchiveTypeEnabled${1}>${2:Contents}</mt:IfArchiveTypeEnabled>"),
            ("mt:IfBlog\tMT[C]", "mt:IfBlog${1}>${2:Contents}</mt:IfBlog>"),
            ("mt:IfCategory\tMT[C]", "mt:IfCategory${1}>${2:Contents}</mt:IfCategory>"),
            ("mt:IfCommenterIsAuthor\tMT[C]", "mt:IfCommenterIsAuthor${1}>${2:Contents}</mt:IfCommenterIsAuthor>"),
            ("mt:IfCommenterIsEntryAuthor\tMT[C]", "mt:IfCommenterIsEntryAuthor${1}>${2:Contents}</mt:IfCommenterIsEntryAuthor>"),
            ("mt:IfCommenterTrusted\tMT[C]", "mt:IfCommenterTrusted${1}>${2:Contents}</mt:IfCommenterTrusted>"),
            ("mt:IfCommentParent\tMT[C]", "mt:IfCommentParent${1}>${2:Contents}</mt:IfCommentParent>"),
            ("mt:IfCommentReplies\tMT[C]", "mt:IfCommentReplies${1}>${2:Contents}</mt:IfCommentReplies>"),
            ("mt:IfCommentsAccepted\tMT[C]", "mt:IfCommentsAccepted${1}>${2:Contents}</mt:IfCommentsAccepted>"),
            ("mt:IfCommentsActive\tMT[C]", "mt:IfCommentsActive${1}>${2:Contents}</mt:IfCommentsActive>"),
            ("mt:IfCommentsAllowed\tMT[C]", "mt:IfCommentsAllowed${1}>${2:Contents}</mt:IfCommentsAllowed>"),
            ("mt:IfCommentsModerated\tMT[C]", "mt:IfCommentsModerated${1}>${2:Contents}</mt:IfCommentsModerated>"),
            ("mt:IfCurrentPage\tMT[C]", "mt:IfCurrentPage${1}>${2:Contents}</mt:IfCurrentPage>"),
            ("mt:IfDynamic\tMT[C]", "mt:IfDynamic${1}>${2:Contents}</mt:IfDynamic>"),
            ("mt:IfFolder\tMT[C]", "mt:IfFolder${1}>${2:Contents}</mt:IfFolder>"),
            ("mt:IfImageSupport\tMT[C]", "mt:IfImageSupport${1}>${2:Contents}</mt:IfImageSupport>"),
            ("mt:IfIsAncestor\tMT[C]", "mt:IfIsAncestor${1}>${2:Contents}</mt:IfIsAncestor>"),
            ("mt:IfIsDescendant\tMT[C]", "mt:IfIsDescendant${1}>${2:Contents}</mt:IfIsDescendant>"),
            ("mt:IfLoggedIn\tMT[C]", "mt:IfLoggedIn${1}>${2:Contents}</mt:IfLoggedIn>"),
            ("mt:IfLogin\tDynamicMTML[C]", "mt:IfLogin${1}>${2}</mt:IfLogin>"),
            ("mt:IfMaxResultsCutoff\tMT[C]", "mt:IfMaxResultsCutoff${1}>${2:Contents}</mt:IfMaxResultsCutoff>"),
            ("mt:IfMoreResults\tMT[C]", "mt:IfMoreResults${1}>${2:Contents}</mt:IfMoreResults>"),
            ("mt:IfNeedEmail\tMT[C]", "mt:IfNeedEmail${1}>${2:Contents}</mt:IfNeedEmail>"),
            ("mt:IfNonEmpty\tMT[C]", "mt:IfNonEmpty${1}>${2:Contents}</mt:IfNonEmpty>"),
            ("mt:IfNonZero\tMT[C]", "mt:IfNonZero${1}>${2:Contents}</mt:IfNonZero>"),
            ("mt:IfPingsAccepted\tMT[C]", "mt:IfPingsAccepted${1}>${2:Contents}</mt:IfPingsAccepted>"),
            ("mt:IfPingsActive\tMT[C]", "mt:IfPingsActive${1}>${2:Contents}</mt:IfPingsActive>"),
            ("mt:IfPingsAllowed\tMT[C]", "mt:IfPingsAllowed${1}>${2:Contents}</mt:IfPingsAllowed>"),
            ("mt:IfPingsModerated\tMT[C]", "mt:IfPingsModerated${1}>${2:Contents}</mt:IfPingsModerated>"),
            ("mt:IfPreviousResults\tMT[C]", "mt:IfPreviousResults${1}>${2:Contents}</mt:IfPreviousResults>"),
            ("mt:IfRegistrationAllowed\tMT[C]", "mt:IfRegistrationAllowed${1}>${2:Contents}</mt:IfRegistrationAllowed>"),
            ("mt:IfRegistrationNotRequired\tMT[C]", "mt:IfRegistrationNotRequired${1}>${2:Contents}</mt:IfRegistrationNotRequired>"),
            ("mt:IfRegistrationRequired\tMT[C]", "mt:IfRegistrationRequired${1}>${2:Contents}</mt:IfRegistrationRequired>"),
            ("mt:IfRequireCommentEmails\tMT[C]", "mt:IfRequireCommentEmails${1}>${2:Contents}</mt:IfRequireCommentEmails>"),
            ("mt:IfStatic\tMT[C]", "mt:IfStatic${1}>${2:Contents}</mt:IfStatic>"),
            ("mt:IfStraightSearch\tMT[C]", "mt:IfStraightSearch${1}>${2:Contents}</mt:IfStraightSearch>"),
            ("mt:IfTagSearch\tMT[C]", "mt:IfTagSearch${1}>${2:Contents}</mt:IfTagSearch>"),
            ("mt:IfTypeKeyToken\tMT[C]", "mt:IfTypeKeyToken${1}>${2:Contents}</mt:IfTypeKeyToken>"),
            ("mt:IfUserAgent\tDynamicMTML[C]", "mt:IfUserAgent${1}>${2}</mt:IfUserAgent>"),
            ("mt:IfUserHasPermission\tDynamicMTML[C]", "mt:IfUserHasPermission${1}>${2}</mt:IfUserHasPermission>"),
            ("mt:IfWebsite\tMT[C]", "mt:IfWebsite${1}>${2:Contents}</mt:IfWebsite>"),
            ("mt:MultiBlogIfLocalBlog\tMT[C]", "mt:MultiBlogIfLocalBlog${1}>${2:Contents}</mt:MultiBlogIfLocalBlog>"),
            ("mt:PageIfTagged\tMT[C]", "mt:PageIfTagged${1}>${2:Contents}</mt:PageIfTagged>"),
            ("mt:WebsiteIfCCLicense\tMT[C]", "mt:WebsiteIfCCLicense${1}>${2:Contents}</mt:WebsiteIfCCLicense>"),
            ("mt:WebsiteIfCommentsOpen\tMT[C]", "mt:WebsiteIfCommentsOpen${1}>${2:Contents}</mt:WebsiteIfCommentsOpen>"),
            # Function Tag
            ("mt\tMT[F]", "mt:${1:TagName} />"),
            ("mt:AdminCGIPath\tMT[F]", "mt:AdminCGIPath${1} />"),
            ("mt:AdminScript\tMT[F]", "mt:AdminScript${1} />"),
            ("mt:ArchiveCategory\tMT[F]", "mt:ArchiveCategory${1} />"),
            ("mt:ArchiveCount\tMT[F]", "mt:ArchiveCount${1} />"),
            ("mt:ArchiveDate\tMT[F]", "mt:ArchiveDate${1} />"),
            ("mt:ArchiveDateEnd\tMT[F]", "mt:ArchiveDateEnd${1} />"),
            ("mt:ArchiveFile\tMT[F]", "mt:ArchiveFile${1} />"),
            ("mt:ArchiveLabel\tMT[F]", "mt:ArchiveLabel${1} />"),
            ("mt:ArchiveLink\tMT[F]", "mt:ArchiveLink${1} />"),
            ("mt:ArchiveTitle\tMT[F]", "mt:ArchiveTitle${1} />"),
            ("mt:ArchiveType\tMT[F]", "mt:ArchiveType${1} />"),
            ("mt:ArchiveTypeLabel\tMT[F]", "mt:ArchiveTypeLabel${1} />"),
            ("mt:AssetAddedBy\tMT[F]", "mt:AssetAddedBy${1} />"),
            ("mt:AssetCount\tMT[F]", "mt:AssetCount${1} />"),
            ("mt:AssetDateAdded\tMT[F]", "mt:AssetDateAdded${1} />"),
            ("mt:AssetDescription\tMT[F]", "mt:AssetDescription${1} />"),
            ("mt:AssetFileExt\tMT[F]", "mt:AssetFileExt${1} />"),
            ("mt:AssetFileName\tMT[F]", "mt:AssetFileName${1} />"),
            ("mt:AssetFilePath\tMT[F]", "mt:AssetFilePath${1} />"),
            ("mt:AssetID\tMT[F]", "mt:AssetID${1} />"),
            ("mt:AssetLabel\tMT[F]", "mt:AssetLabel${1} />"),
            ("mt:AssetLink\tMT[F]", "mt:AssetLink${1} />"),
            ("mt:AssetMimeType\tMT[F]", "mt:AssetMimeType${1} />"),
            ("mt:AssetProperty\tMT[F]", "mt:AssetProperty${1} />"),
            ("mt:AssetRank\tMT[F]", "mt:AssetRank${1} />"),
            ("mt:AssetScore\tMT[F]", "mt:AssetScore${1} />"),
            ("mt:AssetScoreAvg\tMT[F]", "mt:AssetScoreAvg${1} />"),
            ("mt:AssetScoreCount\tMT[F]", "mt:AssetScoreCount${1} />"),
            ("mt:AssetScoreHigh\tMT[F]", "mt:AssetScoreHigh${1} />"),
            ("mt:AssetScoreLow\tMT[F]", "mt:AssetScoreLow${1} />"),
            ("mt:AssetThumbnailLink\tMT[F]", "mt:AssetThumbnailLink${1} />"),
            ("mt:AssetThumbnailURL\tMT[F]", "mt:AssetThumbnailURL${1} />"),
            ("mt:AssetType\tMT[F]", "mt:AssetType${1} />"),
            ("mt:AssetURL\tMT[F]", "mt:AssetURL${1} />"),
            ("mt:AtomScript\tMT[F]", "mt:AtomScript${1} />"),
            ("mt:AudioCustomFieldDescription\tMT[F]", "mt:AudioCustomFieldDescription${1} />"),
            ("mt:AudioCustomFieldName\tMT[F]", "mt:AudioCustomFieldName${1} />"),
            ("mt:AudioCustomFieldValue\tMT[F]", "mt:AudioCustomFieldValue${1} />"),
            ("mt:AuthorAuthIconURL\tMT[F]", "mt:AuthorAuthIconURL${1} />"),
            ("mt:AuthorAuthType\tMT[F]", "mt:AuthorAuthType${1} />"),
            ("mt:AuthorBasename\tMT[F]", "mt:AuthorBasename${1} />"),
            ("mt:AuthorCommentCount\tMT[F]", "mt:AuthorCommentCount${1} />"),
            ("mt:AuthorCustomFieldDescription\tMT[F]", "mt:AuthorCustomFieldDescription${1} />"),
            ("mt:AuthorCustomFieldName\tMT[F]", "mt:AuthorCustomFieldName${1} />"),
            ("mt:AuthorCustomFieldValue\tMT[F]", "mt:AuthorCustomFieldValue${1} />"),
            ("mt:AuthorDisplayName\tMT[F]", "mt:AuthorDisplayName${1} />"),
            ("mt:AuthorEmail\tMT[F]", "mt:AuthorEmail${1} />"),
            ("mt:AuthorEntriesCount\tMT[F]", "mt:AuthorEntriesCount${1} />"),
            ("mt:AuthorEntryCount\tMT[F]", "mt:AuthorEntryCount${1} />"),
            ("mt:AuthorFollowersCount\tMT[F]", "mt:AuthorFollowersCount${1} />"),
            ("mt:AuthorFollowingCount\tMT[F]", "mt:AuthorFollowingCount${1} />"),
            ("mt:AuthorFollowLink\tMT[F]", "mt:AuthorFollowLink${1} />"),
            ("mt:AuthorID\tMT[F]", "mt:AuthorID${1} />"),
            ("mt:AuthorLanguage\tDynamicMTML[F]", "mt:AuthorLanguage${1} />"),
            ("mt:AuthorName\tMT[F]", "mt:AuthorName${1} />"),
            ("mt:AuthorRank\tMT[F]", "mt:AuthorRank${1} />"),
            ("mt:AuthorScore\tMT[F]", "mt:AuthorScore${1} />"),
            ("mt:AuthorScoreAvg\tMT[F]", "mt:AuthorScoreAvg${1} />"),
            ("mt:AuthorScoreCount\tMT[F]", "mt:AuthorScoreCount${1} />"),
            ("mt:AuthorScoreHigh\tMT[F]", "mt:AuthorScoreHigh${1} />"),
            ("mt:AuthorScoreLow\tMT[F]", "mt:AuthorScoreLow${1} />"),
            ("mt:AuthorUnFollowLink\tMT[F]", "mt:AuthorUnFollowLink${1} />"),
            ("mt:AuthorURL\tMT[F]", "mt:AuthorURL${1} />"),
            ("mt:AuthorUserpic\tMT[F]", "mt:AuthorUserpic${1} />"),
            ("mt:AuthorUserpicURL\tMT[F]", "mt:AuthorUserpicURL${1} />"),
            ("mt:BlogArchiveURL\tMT[F]", "mt:BlogArchiveURL${1} />"),
            ("mt:BlogCategoryCount\tMT[F]", "mt:BlogCategoryCount${1} />"),
            ("mt:BlogCCLicenseImage\tMT[F]", "mt:BlogCCLicenseImage${1} />"),
            ("mt:BlogCCLicenseURL\tMT[F]", "mt:BlogCCLicenseURL${1} />"),
            ("mt:BlogCommentCount\tMT[F]", "mt:BlogCommentCount${1} />"),
            ("mt:BlogCustomFieldDescription\tMT[F]", "mt:BlogCustomFieldDescription${1} />"),
            ("mt:BlogCustomFieldName\tMT[F]", "mt:BlogCustomFieldName${1} />"),
            ("mt:BlogCustomFieldValue\tMT[F]", "mt:BlogCustomFieldValue${1} />"),
            ("mt:BlogDescription\tMT[F]", "mt:BlogDescription${1} />"),
            ("mt:BlogEntryCount\tMT[F]", "mt:BlogEntryCount${1} />"),
            ("mt:BlogFileExtension\tMT[F]", "mt:BlogFileExtension${1} />"),
            ("mt:BlogHost\tMT[F]", "mt:BlogHost${1} />"),
            ("mt:BlogID\tMT[F]", "mt:BlogID${1} />"),
            ("mt:BlogLanguage\tMT[F]", "mt:BlogLanguage${1} />"),
            ("mt:BlogName\tMT[F]", "mt:BlogName${1} />"),
            ("mt:BlogPageCount\tMT[F]", "mt:BlogPageCount${1} />"),
            ("mt:BlogPingCount\tMT[F]", "mt:BlogPingCount${1} />"),
            ("mt:BlogRelativeURL\tMT[F]", "mt:BlogRelativeURL${1} />"),
            ("mt:BlogSitePath\tMT[F]", "mt:BlogSitePath${1} />"),
            ("mt:BlogTemplateSetID\tMT[F]", "mt:BlogTemplateSetID${1} />"),
            ("mt:BlogThemeID\tMT[F]", "mt:BlogThemeID${1} />"),
            ("mt:BlogTimezone\tMT[F]", "mt:BlogTimezone${1} />"),
            ("mt:BlogURL\tMT[F]", "mt:BlogURL${1} />"),
            ("mt:BuildTemplateID\tMT[F]", "mt:BuildTemplateID${1} />"),
            ("mt:CalendarCellNumber\tMT[F]", "mt:CalendarCellNumber${1} />"),
            ("mt:CalendarDate\tMT[F]", "mt:CalendarDate${1} />"),
            ("mt:CalendarDay\tMT[F]", "mt:CalendarDay${1} />"),
            ("mt:CaptchaFields\tMT[F]", "mt:CaptchaFields${1} />"),
            ("mt:CategoryArchiveLink\tMT[F]", "mt:CategoryArchiveLink${1} />"),
            ("mt:CategoryBasename\tMT[F]", "mt:CategoryBasename${1} />"),
            ("mt:CategoryCommentCount\tMT[F]", "mt:CategoryCommentCount${1} />"),
            ("mt:CategoryCount\tMT[F]", "mt:CategoryCount${1} />"),
            ("mt:CategoryCustomFieldDescription\tMT[F]", "mt:CategoryCustomFieldDescription${1} />"),
            ("mt:CategoryCustomFieldName\tMT[F]", "mt:CategoryCustomFieldName${1} />"),
            ("mt:CategoryCustomFieldValue\tMT[F]", "mt:CategoryCustomFieldValue${1} />"),
            ("mt:CategoryDescription\tMT[F]", "mt:CategoryDescription${1} />"),
            ("mt:CategoryID\tMT[F]", "mt:CategoryID${1} />"),
            ("mt:CategoryLabel\tMT[F]", "mt:CategoryLabel${1} />"),
            ("mt:CategoryTrackbackCount\tMT[F]", "mt:CategoryTrackbackCount${1} />"),
            ("mt:CategoryTrackbackLink\tMT[F]", "mt:CategoryTrackbackLink${1} />"),
            ("mt:CCLicenseRDF\tMT[F]", "mt:CCLicenseRDF${1} />"),
            ("mt:CGIHost\tMT[F]", "mt:CGIHost${1} />"),
            ("mt:CGIPath\tMT[F]", "mt:CGIPath${1} />"),
            ("mt:CGIRelativeURL\tMT[F]", "mt:CGIRelativeURL${1} />"),
            ("mt:CGIServerPath\tMT[F]", "mt:CGIServerPath${1} />"),
            ("mt:CommentAuthor\tMT[F]", "mt:CommentAuthor${1} />"),
            ("mt:CommentAuthorIdentity\tMT[F]", "mt:CommentAuthorIdentity${1} />"),
            ("mt:CommentAuthorLink\tMT[F]", "mt:CommentAuthorLink${1} />"),
            ("mt:CommentBlogID\tMT[F]", "mt:CommentBlogID${1} />"),
            ("mt:CommentBody\tMT[F]", "mt:CommentBody${1} />"),
            ("mt:CommentCustomFieldDescription\tMT[F]", "mt:CommentCustomFieldDescription${1} />"),
            ("mt:CommentCustomFieldName\tMT[F]", "mt:CommentCustomFieldName${1} />"),
            ("mt:CommentCustomFieldValue\tMT[F]", "mt:CommentCustomFieldValue${1} />"),
            ("mt:CommentDate\tMT[F]", "mt:CommentDate${1} />"),
            ("mt:CommentEmail\tMT[F]", "mt:CommentEmail${1} />"),
            ("mt:CommentEntryID\tMT[F]", "mt:CommentEntryID${1} />"),
            ("mt:CommenterAuthIconURL\tMT[F]", "mt:CommenterAuthIconURL${1} />"),
            ("mt:CommenterAuthType\tMT[F]", "mt:CommenterAuthType${1} />"),
            ("mt:CommenterEmail\tMT[F]", "mt:CommenterEmail${1} />"),
            ("mt:CommenterID\tMT[F]", "mt:CommenterID${1} />"),
            ("mt:CommenterName\tMT[F]", "mt:CommenterName${1} />"),
            ("mt:CommenterNameThunk\tMT[F]", "mt:CommenterNameThunk${1} />"),
            ("mt:CommenterURL\tMT[F]", "mt:CommenterURL${1} />"),
            ("mt:CommenterUsername\tMT[F]", "mt:CommenterUsername${1} />"),
            ("mt:CommenterUserpic\tMT[F]", "mt:CommenterUserpic${1} />"),
            ("mt:CommenterUserpicURL\tMT[F]", "mt:CommenterUserpicURL${1} />"),
            ("mt:CommentID\tMT[F]", "mt:CommentID${1} />"),
            ("mt:CommentIP\tMT[F]", "mt:CommentIP${1} />"),
            ("mt:CommentLink\tMT[F]", "mt:CommentLink${1} />"),
            ("mt:CommentName\tMT[F]", "mt:CommentName${1} />"),
            ("mt:CommentOrderNumber\tMT[F]", "mt:CommentOrderNumber${1} />"),
            ("mt:CommentParentID\tMT[F]", "mt:CommentParentID${1} />"),
            ("mt:CommentPreviewAuthor\tMT[F]", "mt:CommentPreviewAuthor${1} />"),
            ("mt:CommentPreviewAuthorLink\tMT[F]", "mt:CommentPreviewAuthorLink${1} />"),
            ("mt:CommentPreviewBody\tMT[F]", "mt:CommentPreviewBody${1} />"),
            ("mt:CommentPreviewDate\tMT[F]", "mt:CommentPreviewDate${1} />"),
            ("mt:CommentPreviewEmail\tMT[F]", "mt:CommentPreviewEmail${1} />"),
            ("mt:CommentPreviewIP\tMT[F]", "mt:CommentPreviewIP${1} />"),
            ("mt:CommentPreviewIsStatic\tMT[F]", "mt:CommentPreviewIsStatic${1} />"),
            ("mt:CommentPreviewURL\tMT[F]", "mt:CommentPreviewURL${1} />"),
            ("mt:CommentRank\tMT[F]", "mt:CommentRank${1} />"),
            ("mt:CommentRepliesRecurse\tMT[F]", "mt:CommentRepliesRecurse${1} />"),
            ("mt:CommentScore\tMT[F]", "mt:CommentScore${1} />"),
            ("mt:CommentScoreAvg\tMT[F]", "mt:CommentScoreAvg${1} />"),
            ("mt:CommentScoreCount\tMT[F]", "mt:CommentScoreCount${1} />"),
            ("mt:CommentScoreHigh\tMT[F]", "mt:CommentScoreHigh${1} />"),
            ("mt:CommentScoreLow\tMT[F]", "mt:CommentScoreLow${1} />"),
            ("mt:CommentScript\tMT[F]", "mt:CommentScript${1} />"),
            ("mt:CommentURL\tMT[F]", "mt:CommentURL${1} />"),
            ("mt:CommunityScript\tMT[F]", "mt:CommunityScript${1} />"),
            ("mt:ConfigFile\tMT[F]", "mt:ConfigFile${1} />"),
            ("mt:CurrentArchiveFile\tDynamicMTML[F]", "mt:CurrentArchiveFile${1} />"),
            ("mt:CurrentArchiveURL\tDynamicMTML[F]", "mt:CurrentArchiveURL${1} />"),
            ("mt:CurrentPage\tMT[F]", "mt:CurrentPage${1} />"),
            ("mt:CustomFieldBasename\tMT[F]", "mt:CustomFieldBasename${1} />"),
            ("mt:CustomFieldDescription\tMT[F]", "mt:CustomFieldDescription${1} />"),
            ("mt:CustomFieldHTML\tMT[F]", "mt:CustomFieldHTML${1} />"),
            ("mt:CustomFieldName\tMT[F]", "mt:CustomFieldName${1} />"),
            ("mt:CustomFieldValue\tMT[F]", "mt:CustomFieldValue${1} />"),
            ("mt:Date\tMT[F]", "mt:Date${1} />"),
            ("mt:DefaultLanguage\tMT[F]", "mt:DefaultLanguage${1} />"),
            ("mt:EntriesCount\tMT[F]", "mt:EntriesCount${1} />"),
            ("mt:EntryAtomID\tMT[F]", "mt:EntryAtomID${1} />"),
            ("mt:EntryAudio\tMT[F]", "mt:EntryAudio${1} />"),
            ("mt:EntryAuthor\tMT[F]", "mt:EntryAuthor${1} />"),
            ("mt:EntryAuthorDisplayName\tMT[F]", "mt:EntryAuthorDisplayName${1} />"),
            ("mt:EntryAuthorEmail\tMT[F]", "mt:EntryAuthorEmail${1} />"),
            ("mt:EntryAuthorID\tMT[F]", "mt:EntryAuthorID${1} />"),
            ("mt:EntryAuthorLink\tMT[F]", "mt:EntryAuthorLink${1} />"),
            ("mt:EntryAuthorNickname\tMT[F]", "mt:EntryAuthorNickname${1} />"),
            ("mt:EntryAuthorURL\tMT[F]", "mt:EntryAuthorURL${1} />"),
            ("mt:EntryAuthorUsername\tMT[F]", "mt:EntryAuthorUsername${1} />"),
            ("mt:EntryAuthorUserpic\tMT[F]", "mt:EntryAuthorUserpic${1} />"),
            ("mt:EntryAuthorUserpicURL\tMT[F]", "mt:EntryAuthorUserpicURL${1} />"),
            ("mt:EntryBasename\tMT[F]", "mt:EntryBasename${1} />"),
            ("mt:EntryBlogDescription\tMT[F]", "mt:EntryBlogDescription${1} />"),
            ("mt:EntryBlogID\tMT[F]", "mt:EntryBlogID${1} />"),
            ("mt:EntryBlogName\tMT[F]", "mt:EntryBlogName${1} />"),
            ("mt:EntryBlogURL\tMT[F]", "mt:EntryBlogURL${1} />"),
            ("mt:EntryBody\tMT[F]", "mt:EntryBody${1} />"),
            ("mt:EntryCategory\tMT[F]", "mt:EntryCategory${1} />"),
            ("mt:EntryClass\tMT[F]", "mt:EntryClass${1} />"),
            ("mt:EntryClassLabel\tMT[F]", "mt:EntryClassLabel${1} />"),
            ("mt:EntryCommentCount\tMT[F]", "mt:EntryCommentCount${1} />"),
            ("mt:EntryCreatedDate\tMT[F]", "mt:EntryCreatedDate${1} />"),
            ("mt:EntryCustomFieldDescription\tMT[F]", "mt:EntryCustomFieldDescription${1} />"),
            ("mt:EntryCustomFieldName\tMT[F]", "mt:EntryCustomFieldName${1} />"),
            ("mt:EntryCustomFieldValue\tMT[F]", "mt:EntryCustomFieldValue${1} />"),
            ("mt:EntryDate\tMT[F]", "mt:EntryDate${1} />"),
            ("mt:EntryEditLink\tMT[F]", "mt:EntryEditLink${1} />"),
            ("mt:EntryEmbedCode\tMT[F]", "mt:EntryEmbedCode${1} />"),
            ("mt:EntryExcerpt\tMT[F]", "mt:EntryExcerpt${1} />"),
            ("mt:EntryFlag\tMT[F]", "mt:EntryFlag${1} />"),
            ("mt:EntryID\tMT[F]", "mt:EntryID${1} />"),
            ("mt:EntryKeywords\tMT[F]", "mt:EntryKeywords${1} />"),
            ("mt:EntryLink\tMT[F]", "mt:EntryLink${1} />"),
            ("mt:EntryLinkURL\tMT[F]", "mt:EntryLinkURL${1} />"),
            ("mt:EntryModifiedDate\tMT[F]", "mt:EntryModifiedDate${1} />"),
            ("mt:EntryMore\tMT[F]", "mt:EntryMore${1} />"),
            ("mt:EntryPermalink\tMT[F]", "mt:EntryPermalink${1} />"),
            ("mt:EntryPhoto\tMT[F]", "mt:EntryPhoto${1} />"),
            ("mt:EntryPostType\tMT[F]", "mt:EntryPostType${1} />"),
            ("mt:EntryRank\tMT[F]", "mt:EntryRank${1} />"),
            ("mt:EntryRawPostType\tMT[F]", "mt:EntryRawPostType${1} />"),
            ("mt:EntryRecommendedTotal\tMT[F]", "mt:EntryRecommendedTotal${1} />"),
            ("mt:EntryRecommendVoteLink\tMT[F]", "mt:EntryRecommendVoteLink${1} />"),
            ("mt:EntryScore\tMT[F]", "mt:EntryScore${1} />"),
            ("mt:EntryScoreAvg\tMT[F]", "mt:EntryScoreAvg${1} />"),
            ("mt:EntryScoreCount\tMT[F]", "mt:EntryScoreCount${1} />"),
            ("mt:EntryScoreHigh\tMT[F]", "mt:EntryScoreHigh${1} />"),
            ("mt:EntryScoreLow\tMT[F]", "mt:EntryScoreLow${1} />"),
            ("mt:EntryStatus\tMT[F]", "mt:EntryStatus${1} />"),
            ("mt:EntryStatusInt\tDynamicMTML[F]", "mt:EntryStatusInt${1} />"),
            ("mt:EntryTitle\tMT[F]", "mt:EntryTitle${1: escape=\"html\"} />"),
            ("mt:EntryTrackbackCount\tMT[F]", "mt:EntryTrackbackCount${1} />"),
            ("mt:EntryTrackbackData\tMT[F]", "mt:EntryTrackbackData${1} />"),
            ("mt:EntryTrackbackID\tMT[F]", "mt:EntryTrackbackID${1} />"),
            ("mt:EntryTrackbackLink\tMT[F]", "mt:EntryTrackbackLink${1} />"),
            ("mt:ErrorMessage\tMT[F]", "mt:ErrorMessage${1} />"),
            ("mt:FeedbackScore\tMT[F]", "mt:FeedbackScore${1} />"),
            ("mt:FeedEntryLink\tMT[F]", "mt:FeedEntryLink${1} />"),
            ("mt:FeedEntryTitle\tMT[F]", "mt:FeedEntryTitle${1} />"),
            ("mt:FeedInclude\tMT[F]", "mt:FeedInclude${1} />"),
            ("mt:FeedLink\tMT[F]", "mt:FeedLink${1} />"),
            ("mt:FeedTitle\tMT[F]", "mt:FeedTitle${1} />"),
            ("mt:FileCustomFieldDescription\tMT[F]", "mt:FileCustomFieldDescription${1} />"),
            ("mt:FileCustomFieldName\tMT[F]", "mt:FileCustomFieldName${1} />"),
            ("mt:FileCustomFieldValue\tMT[F]", "mt:FileCustomFieldValue${1} />"),
            ("mt:FileTemplate\tMT[F]", "mt:FileTemplate${1} />"),
            ("mt:FolderBasename\tMT[F]", "mt:FolderBasename${1} />"),
            ("mt:FolderCount\tMT[F]", "mt:FolderCount${1} />"),
            ("mt:FolderCustomFieldDescription\tMT[F]", "mt:FolderCustomFieldDescription${1} />"),
            ("mt:FolderCustomFieldName\tMT[F]", "mt:FolderCustomFieldName${1} />"),
            ("mt:FolderCustomFieldValue\tMT[F]", "mt:FolderCustomFieldValue${1} />"),
            ("mt:FolderDescription\tMT[F]", "mt:FolderDescription${1} />"),
            ("mt:FolderID\tMT[F]", "mt:FolderID${1} />"),
            ("mt:FolderLabel\tMT[F]", "mt:FolderLabel${1} />"),
            ("mt:FolderPath\tMT[F]", "mt:FolderPath${1} />"),
            ("mt:GetVar\tMT[F]", "mt:GetVar${1} />"),
            ("mt:HTTPContentType\tMT[F]", "mt:HTTPContentType${1} />"),
            ("mt:ImageCustomFieldDescription\tMT[F]", "mt:ImageCustomFieldDescription${1} />"),
            ("mt:ImageCustomFieldName\tMT[F]", "mt:ImageCustomFieldName${1} />"),
            ("mt:ImageCustomFieldValue\tMT[F]", "mt:ImageCustomFieldValue${1} />"),
            ("mt:ImageHeight\tMT[F]", "mt:ImageHeight${1} />"),
            ("mt:ImageURL\tMT[F]", "mt:ImageURL${1} />"),
            ("mt:ImageWidth\tMT[F]", "mt:ImageWidth${1} />"),
            ("mt:Include\tMT[F]", "mt:Include module=\"${1:Module Name}\" />"),
            ("mt:Include module\tMT[F]", "mt:Include module=\"${1:module}\" />"),
            ("mt:IndexBasename\tMT[F]", "mt:IndexBasename${1} />"),
            ("mt:IndexLink\tMT[F]", "mt:IndexLink${1} />"),
            ("mt:IndexName\tMT[F]", "mt:IndexName${1} />"),
            ("mt:Link\tMT[F]", "mt:Link${1} />"),
            ("mt:MaxResults\tMT[F]", "mt:MaxResults${1} />"),
            ("mt:NextLink\tMT[F]", "mt:NextLink${1} />"),
            ("mt:NotifyScript\tMT[F]", "mt:NotifyScript${1} />"),
            ("mt:OtherProfileVar\tMT[F]", "mt:OtherProfileVar${1} />"),
            ("mt:PageAuthorDisplayName\tMT[F]", "mt:PageAuthorDisplayName${1} />"),
            ("mt:PageAuthorEmail\tMT[F]", "mt:PageAuthorEmail${1} />"),
            ("mt:PageAuthorLink\tMT[F]", "mt:PageAuthorLink${1} />"),
            ("mt:PageAuthorURL\tMT[F]", "mt:PageAuthorURL${1} />"),
            ("mt:PageBasename\tMT[F]", "mt:PageBasename${1} />"),
            ("mt:PageBody\tMT[F]", "mt:PageBody${1} />"),
            ("mt:PageCustomFieldDescription\tMT[F]", "mt:PageCustomFieldDescription${1} />"),
            ("mt:PageCustomFieldName\tMT[F]", "mt:PageCustomFieldName${1} />"),
            ("mt:PageCustomFieldValue\tMT[F]", "mt:PageCustomFieldValue${1} />"),
            ("mt:PageDate\tMT[F]", "mt:PageDate${1} />"),
            ("mt:PageExcerpt\tMT[F]", "mt:PageExcerpt${1} />"),
            ("mt:PageID\tMT[F]", "mt:PageID${1} />"),
            ("mt:PageKeywords\tMT[F]", "mt:PageKeywords${1} />"),
            ("mt:PageModifiedDate\tMT[F]", "mt:PageModifiedDate${1} />"),
            ("mt:PageMore\tMT[F]", "mt:PageMore${1} />"),
            ("mt:PagePermalink\tMT[F]", "mt:PagePermalink${1} />"),
            ("mt:PagerLink\tMT[F]", "mt:PagerLink${1} />"),
            ("mt:PageTitle\tMT[F]", "mt:PageTitle${1: escape=\"html\"} />"),
            ("mt:PingBlogName\tMT[F]", "mt:PingBlogName${1} />"),
            ("mt:PingDate\tMT[F]", "mt:PingDate${1} />"),
            ("mt:PingExcerpt\tMT[F]", "mt:PingExcerpt${1} />"),
            ("mt:PingID\tMT[F]", "mt:PingID${1} />"),
            ("mt:PingIP\tMT[F]", "mt:PingIP${1} />"),
            ("mt:PingRank\tMT[F]", "mt:PingRank${1} />"),
            ("mt:PingScore\tMT[F]", "mt:PingScore${1} />"),
            ("mt:PingScoreAvg\tMT[F]", "mt:PingScoreAvg${1} />"),
            ("mt:PingScoreCount\tMT[F]", "mt:PingScoreCount${1} />"),
            ("mt:PingScoreHigh\tMT[F]", "mt:PingScoreHigh${1} />"),
            ("mt:PingScoreLow\tMT[F]", "mt:PingScoreLow${1} />"),
            ("mt:PingsSentURL\tMT[F]", "mt:PingsSentURL${1} />"),
            ("mt:PingTitle\tMT[F]", "mt:PingTitle${1} />"),
            ("mt:PingURL\tMT[F]", "mt:PingURL${1} />"),
            ("mt:PreviousLink\tMT[F]", "mt:PreviousLink${1} />"),
            ("mt:ProductName\tMT[F]", "mt:ProductName${1} />"),
            ("mt:PublishCharset\tMT[F]", "mt:PublishCharset${1} />"),
            ("mt:Query\tDynamicMTML[F]", "mt:Query${1} />"),
            ("mt:Rand\tDynamicMTML[F]", "mt:Rand${1} />"),
            ("mt:ReferralKeyword\tDynamicMTML[F]", "mt:ReferralKeyword${1} />"),
            ("mt:RemoteSignInLink\tMT[F]", "mt:RemoteSignInLink${1} />"),
            ("mt:RemoteSignOutLink\tMT[F]", "mt:RemoteSignOutLink${1} />"),
            ("mt:SearchIncludeBlogs\tMT[F]", "mt:SearchIncludeBlogs${1} />"),
            ("mt:SearchMaxResults\tMT[F]", "mt:SearchMaxResults${1} />"),
            ("mt:SearchResultCount\tMT[F]", "mt:SearchResultCount${1} />"),
            ("mt:SearchScript\tMT[F]", "mt:SearchScript${1} />"),
            ("mt:SearchString\tMT[F]", "mt:SearchString${1} />"),
            ("mt:SearchTemplateID\tMT[F]", "mt:SearchTemplateID${1} />"),
            ("mt:SetVar\tMT[F]", "mt:SetVar name=\"${1:VariableName}\" value=\"${2:Value}\" />"),
            ("mt:SignOnURL\tMT[F]", "mt:SignOnURL${1} />"),
            ("mt:SmartyPantsVersion\tMT[F]", "mt:SmartyPantsVersion${1} />"),
            ("mt:StaticFilePath\tMT[F]", "mt:StaticFilePath${1} />"),
            ("mt:StaticWebPath\tMT[F]", "mt:StaticWebPath${1} />"),
            ("mt:StreamAction\tMT[F]", "mt:StreamAction${1} />"),
            ("mt:StreamActionDate\tMT[F]", "mt:StreamActionDate${1} />"),
            ("mt:StreamActionID\tMT[F]", "mt:StreamActionID${1} />"),
            ("mt:StreamActionModifiedDate\tMT[F]", "mt:StreamActionModifiedDate${1} />"),
            ("mt:StreamActionThumbnailURL\tMT[F]", "mt:StreamActionThumbnailURL${1} />"),
            ("mt:StreamActionTitle\tMT[F]", "mt:StreamActionTitle${1} />"),
            ("mt:StreamActionVar\tMT[F]", "mt:StreamActionVar${1} />"),
            ("mt:SubCategoryPath\tMT[F]", "mt:SubCategoryPath${1} />"),
            ("mt:SubCatsRecurse\tMT[F]", "mt:SubCatsRecurse${1} />"),
            ("mt:SubFolderRecurse\tMT[F]", "mt:SubFolderRecurse${1} />"),
            ("mt:SupportDirectoryURL\tMT[F]", "mt:SupportDirectoryURL${1} />"),
            ("mt:TagCount\tMT[F]", "mt:TagCount${1} />"),
            ("mt:TagID\tMT[F]", "mt:TagID${1} />"),
            ("mt:TagLabel\tMT[F]", "mt:TagLabel${1} />"),
            ("mt:TagName\tMT[F]", "mt:TagName${1} />"),
            ("mt:TagRank\tMT[F]", "mt:TagRank${1} />"),
            ("mt:TagSearchLink\tMT[F]", "mt:TagSearchLink${1} />"),
            ("mt:TemplateCreatedOn\tMT[F]", "mt:TemplateCreatedOn${1} />"),
            ("mt:TemplateCustomFieldDescription\tMT[F]", "mt:TemplateCustomFieldDescription${1} />"),
            ("mt:TemplateCustomFieldName\tMT[F]", "mt:TemplateCustomFieldName${1} />"),
            ("mt:TemplateCustomFieldValue\tMT[F]", "mt:TemplateCustomFieldValue${1} />"),
            ("mt:TemplateNote\tMT[F]", "mt:TemplateNote value=\"${1:Comment}\" />"),
            ("mt:TextileHeadOffset\tMT[F]", "mt:TextileHeadOffset${1} />"),
            ("mt:TextileOptions\tMT[F]", "mt:TextileOptions${1} />"),
            ("mt:TotalPages\tMT[F]", "mt:TotalPages${1} />"),
            ("mt:TrackbackScript\tMT[F]", "mt:TrackbackScript${1} />"),
            ("mt:Trans\tDynamicMTML[F]", "mt:Trans${1} />"),
            ("mt:TypeKeyToken\tMT[F]", "mt:TypeKeyToken${1} />"),
            ("mt:UserAgent\tDynamicMTML[F]", "mt:UserAgent${1} />"),
            ("mt:Var\tMT[F]", "mt:Var${1} />"),
            ("mt:Var\tMT[F]", "mt:Var name=\"${1:name}\" />"),
            ("mt:Version\tMT[F]", "mt:Version${1} />"),
            ("mt:VideoCustomFieldDescription\tMT[F]", "mt:VideoCustomFieldDescription${1} />"),
            ("mt:VideoCustomFieldName\tMT[F]", "mt:VideoCustomFieldName${1} />"),
            ("mt:VideoCustomFieldValue\tMT[F]", "mt:VideoCustomFieldValue${1} />"),
            ("mt:WebsiteCCLicenseImage\tMT[F]", "mt:WebsiteCCLicenseImage${1} />"),
            ("mt:WebsiteCCLicenseURL\tMT[F]", "mt:WebsiteCCLicenseURL${1} />"),
            ("mt:WebsiteCommentCount\tMT[F]", "mt:WebsiteCommentCount${1} />"),
            ("mt:WebsiteCustomFieldDescription\tMT[F]", "mt:WebsiteCustomFieldDescription${1} />"),
            ("mt:WebsiteCustomFieldName\tMT[F]", "mt:WebsiteCustomFieldName${1} />"),
            ("mt:WebsiteCustomFieldValue\tMT[F]", "mt:WebsiteCustomFieldValue${1} />"),
            ("mt:WebsiteDescription\tMT[F]", "mt:WebsiteDescription${1} />"),
            ("mt:WebsiteFileExtension\tMT[F]", "mt:WebsiteFileExtension${1} />"),
            ("mt:WebsiteHost\tMT[F]", "mt:WebsiteHost${1} />"),
            ("mt:WebsiteID\tMT[F]", "mt:WebsiteID${1} />"),
            ("mt:WebsiteLanguage\tMT[F]", "mt:WebsiteLanguage${1} />"),
            ("mt:WebsiteName\tMT[F]", "mt:WebsiteName${1} />"),
            ("mt:WebsitePageCount\tMT[F]", "mt:WebsitePageCount${1} />"),
            ("mt:WebsitePath\tMT[F]", "mt:WebsitePath${1} />"),
            ("mt:WebsitePingCount\tMT[F]", "mt:WebsitePingCount${1} />"),
            ("mt:WebsiteRelativeURL\tMT[F]", "mt:WebsiteRelativeURL${1} />"),
            ("mt:WebsiteThemeID\tMT[F]", "mt:WebsiteThemeID${1} />"),
            ("mt:WebsiteTimezone\tMT[F]", "mt:WebsiteTimezone${1} />"),
            ("mt:WebsiteURL\tMT[F]", "mt:WebsiteURL${1} />"),
            ("mt:WidgetManager\tMT[F]", "mt:WidgetManager${1} />"),
            ("mt:WidgetSet\tMT[F]", "mt:WidgetSet${1} />"),
            ("mt:XMLRPCScript\tMT[F]", "mt:XMLRPCScript${1} />"),
            ("mtapp:ActionBar\tMT[F]", "mtapp:ActionBar${1} />"),
            ("mtapp:Link\tMT[F]", "mtapp:Link${1} />"),
            ("mtapp:ListFilters\tMT[F]", "mtapp:ListFilters${1} />"),
            ("mtapp:PageActions\tMT[F]", "mtapp:PageActions${1} />"),
            ("mtml\tDynamicMTML[F]", "mtml tag='${1:/}mt:${2:TagName}'${3: params=''} />\n")
        ], sublime.INHIBIT_WORD_COMPLETIONS | sublime.INHIBIT_EXPLICIT_COMPLETIONS)
