import sublime, sublime_plugin
import re
def match(rex, str):
    m = rex.match(str)
    if m:
        return m.group(0)
    else:
        return None
class ModifierCompletions(sublime_plugin.EventListener):
    def on_query_completions(self, view, prefix, locations):
        # Only trigger within HTML
        # if not view.match_selector(locations[0],
        #         "text.html - source"):
        #     return []
        pt = locations[0] - len(prefix) - 1
        ch = view.substr(sublime.Region(pt, pt + 1))
        if ch != ' ':
            return []
        return ([
            ("action=\"url\"\tMT[M]", "action=\"${1:url}\""),
            ("append=\"1\"\tMT[M]", "append=\"${1:1}\""),
            ("author=\"author_foo\"\tMT[M]", "author=\"${1:author_foo}\""),
            ("author=\"author_user_name\"\tMT[M]", "author=\"${1:author_user_name}\""),
            ("authors=\"author_user_name\"\tMT[M]", "authors=\"${1:author_user_name}\""),
            ("author_id=\"id\"\tMT[M]", "author_id=\"${1:id}\""),
            ("author_ids=\"author_id\"\tMT[M]", "author_ids=\"${1:author_id}\""),
            ("blog_id=\"id\"\tMT[M]", "blog_id=\"${1:id}\""),
            ("blog_ids=\"all\"\tMT[M]", "blog_ids=\"${1:all}\""),
            ("blog_ids=\"children\"\tMT[M]", "blog_ids=\"${1:children}\""),
            ("blog_ids=\"ID\"\tMT[M]", "blog_ids=\"${1:ID}\""),
            ("blog_ids=\"siblings\"\tMT[M]", "blog_ids=\"${1:siblings}\""),
            ("by=\"action\"\tMT[M]", "by=\"${1:action}\""),
            ("by=\"date\"\tMT[M]", "by=\"${1:date}\""),
            ("by=\"service\"\tMT[M]", "by=\"${1:service}\""),
            ("by=\"stream\"\tMT[M]", "by=\"${1:stream}\""),
            ("by_blog=\"1\"\tMT[M]", "by_blog=\"${1:1}\""),
            ("by_user=\"1\"\tMT[M]", "by_user=\"${1:1}\""),
            ("cache=\"1\"\tMT[M]", "cache=\"${1:1}\""),
            ("cache_key=\"cache_key\"\tMT[M]", "cache_key=\"${1:cache_key}\""),
            ("cache_prefix=\"key_foo\"\tMT[M]", "cache_prefix=\"${1:key_foo}\""),
            ("capitalize=\"1\"\tMT[M]", "capitalize=\"1\""),
            ("cat=\"\"\tMT[M]", "cat=\"${1}\""),
            ("count_characters=\"1\"\tMT[M]", "count_characters=\"1\""),
            ("count_paragraphs=\"1\"\tMT[M]", "count_paragraphs=\"1\""),
            ("count_words=\"\"\tMT[M]", "count_words=\"${1}\""),
            ("days=\"N\"\tMT[M]", "days=\"${1:N}\""),
            ("decode_html=\"1\"\tMT[M]", "decode_html=\"1\""),
            ("decode_xml=\"1\"\tMT[M]", "decode_xml=\"1\""),
            ("direction=\"ascend\"\tMT[M]", "direction=\"${1:ascend}\""),
            ("direction=\"descend\"\tMT[M]", "direction=\"${1:descend}\""),
            ("dirify=\"1\"\tMT[M]", "dirify=\"1\""),
            ("display_name=\"display_name\"\tMT[M]", "display_name=\"${1:display_name}\""),
            ("display_names=\"display_name\"\tMT[M]", "display_names=\"${1:display_name}\""),
            ("element_id=\"id\"\tMT[M]", "element_id=\"${1:id}\""),
            ("encode_js=\"1\"\tMT[M]", "encode_js=\"1\""),
            ("encode_php=\"1\"\tMT[M]", "encode_php=\"1\""),
            ("encode_sha1=\"1\"\tMT[M]", "encode_sha1=\"1\""),
            ("encode_url=\"1\"\tMT[M]", "encode_url=\"1\""),
            ("encode_xml=\"1\"\tMT[M]", "encode_xml=\"1\""),
            ("enctype=\"enctype_foo\"\tMT[M]", "enctype=\"${1:enctype_foo}\""),
            ("escape=\"html\"\tMT[M]", "escape=\"html\""),
            ("escape=\"javascript\"\tMT[M]", "escape=\"javascript\""),
            ("escape=\"mail\"\tMT[M]", "escape=\"mail\""),
            ("escape=\"url\"\tMT[M]", "escape=\"url\""),
            ("exclude_blogs=\"ID\"\tMT[M]", "exclude_blogs=\"${1:ID}\""),
            ("field:customfieldbasename=\"foo\"\tMT[M]", "field:customfieldbasename=\"${1:foo}\""),
            ("filters=\"\"\tMT[M]", "filters=\"${1}\""),
            ("flavor=\"html\"\tMT[M]", "flavor=\"${1:html}\""),
            ("flavor=\"html/css\"\tMT[M]", "flavor=\"${1:html/css}\""),
            ("flavor=\"xhtml1\"\tMT[M]", "flavor=\"${1:xhtml1}\""),
            ("flavor=\"xhtml2\"\tMT[M]", "flavor=\"${1:xhtml2}\""),
            ("folder=\"folder_foo\"\tMT[M]", "folder=\"${1:folder_foo}\""),
            ("format=\"format\"\tMT[M]", "format=\"${1:format}\""),
            ("format_name=\"format_name\"\tMT[M]", "format_name=\"${1:format_name}\""),
            ("global=\"1\"\tMT[M]", "global=\"${1:1}\""),
            ("glue=\"foo\"\tMT[M]", "glue=\"${1:foo}\""),
            ("head_offset=\"N\"\tMT[M]", "head_offset=\"${1:N}\""),
            ("highlightingsearchword=\"\"\tDynamicMTML[M]", "highlightingsearchword=\"${1}\""),
            ("html_tag=\"element_foo\"\tMT[M]", "html_tag=\"${1:element_foo}\""),
            ("id=\"id\"\tMT[M]", "id=\"${1:id}\""),
            ("identifier=\"index_template_identifier\"\tMT[M]", "identifier=\"${1:index_template_identifier}\""),
            ("include_blogs=\"all\"\tMT[M]", "include_blogs=\"${1:all}\""),
            ("include_blogs=\"children\"\tMT[M]", "include_blogs=\"${1:children}\""),
            ("include_blogs=\"ID\"\tMT[M]", "include_blogs=\"${1:ID}\""),
            ("include_blogs=\"siblings\"\tMT[M]", "include_blogs=\"${1:siblings}\""),
            ("include_subfolders=\"1\"\tMT[M]", "include_subfolders=\"${1:1}\""),
            ("include_with_website=\"1\"\tMT[M]", "include_with_website=\"${1:1}\""),
            ("indent=\"1\"\tMT[M]", "indent=\"1\""),
            ("intval=\"\"\tDynamicMTML[M]", "intval=\"${1}\""),
            ("key=\"cache_key\"\tMT[M]", "key=\"${1:cache_key}\""),
            ("lastn=\"N\"\tMT[M]", "lastn=\"${1:N}\""),
            ("limit=\"N\"\tMT[M]", "limit=\"${1:N}\""),
            ("lower_case=\"1\"\tMT[M]", "lower_case=\"1\""),
            ("ltrim=\"1\"\tMT[M]", "ltrim=\"1\""),
            ("make_seo_basename=\"\"\tDynamicMTML[M]", "make_seo_basename=\"${1}\""),
            ("method=\"get\"\tMT[M]", "method=\"${1:get}\""),
            ("method=\"post\"\tMT[M]", "method=\"${1:post}\""),
            ("mteval=\"1\"\tMT[M]", "mteval=\"1\""),
            ("name=\"foo\"\tMT[M]", "name=\"${1:foo}\""),
            ("namespace=\"foo\"\tMT[M]", "namespace=\"${1:foo}\""),
            ("nl2br=\"xhtml\"\tMT[M]", "nl2br=\"${1:xhtml}\""),
            ("nofollowfy=\"1\"\tMT[M]", "nofollowfy=\"1\""),
            ("none=\"text\"\tMT[M]", "none=\"${1:text}\""),
            ("no_folder=\"1\"\tMT[M]", "no_folder=\"${1:1}\""),
            ("numify=\"1\"\tMT[M]", "numify=\"1\""),
            ("object_ds=\"\"\tMT[M]", "object_ds=\"${1:}\""),
            ("object_id=\"id\"\tMT[M]", "object_id=\"${1:id}\""),
            ("object_type=\"foo\"\tMT[M]", "object_type=\"${1:foo}\""),
            ("offset=\"N\"\tMT[M]", "offset=\"${1:N}\""),
            ("parent=\"1\"\tMT[M]", "parent=\"${1:1}\""),
            ("period=\"Sec\"\tMT[M]", "period=\"${1:Sec}\""),
            ("plural=\"text\"\tMT[M]", "plural=\"${1:text}\""),
            ("prepend=\"1\"\tMT[M]", "prepend=\"${1:1}\""),
            ("preserve_spaces=\"1\"\tMT[M]", "preserve_spaces=\"${1:1}\""),
            ("range_incl=\"\"\tMT[M]", "range_incl=\"${1:}\""),
            ("recently_commented_on=\"N\"\tMT[M]", "recently_commented_on=\"${1:N}\""),
            ("regex_replace=\"\"\tMT[M]", "regex_replace=\"${1}\""),
            ("regex_replace=\"//\",\"\"\tMT[M]", "regex_replace=\"/${1:RegExp}/\",\"${2:Replacement}\""),
            ("remove_html=\"1\"\tMT[M]", "remove_html=\"1\""),
            ("replace=\"\"\tMT[M]", "replace=\"${1}\""),
            ("rtrim=\"1\"\tMT[M]", "rtrim=\"1\""),
            ("sanitize=\"1\"\tMT[M]", "sanitize=\"${1:1}\""),
            ("script=\"function_foo\"\tMT[M]", "script=\"${1:function_foo}\""),
            ("service=\"service_id\"\tMT[M]", "service=\"${1:service_id}\""),
            ("setvar=\"\"\tMT[M]", "setvar=\"${1}\""),
            ("singular=\"text\"\tMT[M]", "singular=\"${1:text}\""),
            ("smarty_pants=\"1\"\tMT[M]", "smarty_pants=\"1\""),
            ("smart_dashes=\"1\"\tMT[M]", "smart_dashes=\"1\""),
            ("smart_ellipses=\"1\"\tMT[M]", "smart_ellipses=\"1\""),
            ("smart_quotes=\"1\"\tMT[M]", "smart_quotes=\"1\""),
            ("sort=\"authored_on\"\tMT[M]", "sort=\"${1:authored_on}\""),
            ("sort=\"created_on\"\tMT[M]", "sort=\"${1:created_on}\""),
            ("sort_by=\"author_id\"\tMT[M]", "sort_by=\"${1:author_id}\""),
            ("sort_by=\"created_on\"\tMT[M]", "sort_by=\"${1:created_on}\""),
            ("sort_by=\"excerpt\"\tMT[M]", "sort_by=\"${1:excerpt}\""),
            ("sort_by=\"foo\"\tMT[M]", "sort_by=\"${1:foo}\""),
            ("sort_by=\"modified_on\"\tMT[M]", "sort_by=\"${1:modified_on}\""),
            ("sort_by=\"status\"\tMT[M]", "sort_by=\"${1:status}\""),
            ("sort_by=\"title\"\tMT[M]", "sort_by=\"${1:title}\""),
            ("sort_order=\"ascend\"\tMT[M]", "sort_order=\"${1:ascend}\""),
            ("sort_order=\"descend\"\tMT[M]", "sort_order=\"${1:descend}\""),
            ("space_pad=\"N\"\tMT[M]", "space_pad=\"${1:N}\""),
            ("spacify=\"\"\tMT[M]", "spacify=\"${1}\""),
            ("spam_protect=\"1\"\tMT[M]", "spam_protect=\"1\""),
            ("sprintf=\"\"\tMT[M]", "sprintf=\"${1}\""),
            ("square=\"1\"\tMT[M]", "square=\"${1:1}\""),
            ("ssi=\"1\"\tMT[M]", "ssi=\"${1:1}\""),
            ("stream=\"stream_name\"\tMT[M]", "stream=\"${1:stream_name}\""),
            ("string_format=\"\"\tMT[M]", "string_format=\"${1}\""),
            ("strip=\"\"\tMT[M]", "strip=\"${1}\""),
            ("strip_linefeeds=\"1\"\tMT[M]", "strip_linefeeds=\"1\""),
            ("strip_tags=\"1\"\tMT[M]", "strip_tags=\"1\""),
            ("tag=\"tag_foo\"\tMT[M]", "tag=\"${1:tag_foo}\""),
            ("tags=\"tag_foo\"\tMT[M]", "tags=\"${1:tag_foo}\""),
            ("trim=\"1\"\tMT[M]", "trim=\"1\""),
            ("trimwhitespace=\"\"\tDynamicMTML[M]", "trimwhitespace=\"${1}\""),
            ("trim_spaces=\"1\"\tMT[M]", "trim_spaces=\"${1:1}\""),
            ("trim_to=\"N\"\tMT[M]", "trim_to=\"${1:N}\""),
            ("trim_to=\"N+\"\tMT[M]", "trim_to=\"${1:N}+${2}\""),
            ("type=\"\"\tMT[M]", "type=\"${1:}\""),
            ("unique=\"1\"\tMT[M]", "unique=\"${1:1}\""),
            ("upper_case=\"1\"\tMT[M]", "upper_case=\"1\""),
            ("utc=\"1\"\tMT[M]", "utc=\"${1:1}\""),
            ("value=\"\"\tMT[M]", "value=\"${1:}\""),
            ("var=\"variable_foo\"\tMT[M]", "var=\"${1:variable_foo}\""),
            ("variable_foo=\"value\"\tMT[M]", "variable_foo=\"${1:value}\""),
            ("wrap_text=\"N\"\tMT[M]", "wrap_text=\"${1:N}\""),
            ("zero_pad=\"N\"\tMT[M]", "zero_pad=\"${1:N}\""),
            ("__counter__\tMT[M]", "__counter__"),
            ("__even__\tMT[M]", "__even__"),
            ("__first__\tMT[M]", "__first__"),
            ("__last__\tMT[M]", "__last__"),
            ("__odd__\tMT[M]", "__odd__")
        ], sublime.INHIBIT_WORD_COMPLETIONS | sublime.INHIBIT_EXPLICIT_COMPLETIONS)
class MTTagCompletions(sublime_plugin.EventListener):
    def on_query_completions(self, view, prefix, locations):
        # Only trigger within HTML
        # if not view.match_selector(locations[0],
        #         "text.html - source"):
        #     return []
        pt = locations[0] - len(prefix) - 1
        ch = view.substr(sublime.Region(pt, pt + 1))
        if ch != '<':
            return []
        function_tag_type = view.settings().get('mtml_function_tag_type')
        if function_tag_type == 'dollar':
            tag_open = '\$'
            tag_close = '\$>'
        elif function_tag_type == 'none':
            tag_open = ''
            tag_close = '>'
        else:
            tag_open = ''
            tag_close = ' />'
        # block_tag_break = view.settings().get('mtml_block_tag_break')
        # if block_tag_break:
        #     tag_break = '\n\n'
        # else:
        #     tag_break = ''
        mt_prefix = view.settings().get('mtml_prefix')
        if mt_prefix:
            mt_prefix = view.settings().get('mtml_prefix')
        else:
            mt_prefix = 'mt:'
        return ([
            # Block Tag
            (mt_prefix + "Actions\tMT[B]", mt_prefix + "Actions${1}>${2:Contents}</" + mt_prefix + "Actions>"),
            (mt_prefix + "ActionsComment\tMT[B]", mt_prefix + "ActionsComment${1}>${2:Contents}</" + mt_prefix + "ActionsComment>"),
            (mt_prefix + "ActionsEntry\tMT[B]", mt_prefix + "ActionsEntry${1}>${2:Contents}</" + mt_prefix + "ActionsEntry>"),
            (mt_prefix + "ActionsFavorite\tMT[B]", mt_prefix + "ActionsFavorite${1}>${2:Contents}</" + mt_prefix + "ActionsFavorite>"),
            (mt_prefix + "ActionsFooter\tMT[B]", mt_prefix + "ActionsFooter${1}>${2:Contents}</" + mt_prefix + "ActionsFooter>"),
            (mt_prefix + "ActionsHeader\tMT[B]", mt_prefix + "ActionsHeader${1}>${2:Contents}</" + mt_prefix + "ActionsHeader>"),
            (mt_prefix + "ActionStreams\tMT[B]", mt_prefix + "ActionStreams${1}>${2:Contents}</" + mt_prefix + "ActionStreams>"),
            (mt_prefix + "ArchiveList\tMT[B]", mt_prefix + "ArchiveList${1}>${2:Contents}</" + mt_prefix + "ArchiveList>"),
            (mt_prefix + "ArchiveListFooter\tMT[B]", mt_prefix + "ArchiveListFooter${1}>${2:Contents}</" + mt_prefix + "ArchiveListFooter>"),
            (mt_prefix + "ArchiveListHeader\tMT[B]", mt_prefix + "ArchiveListHeader${1}>${2:Contents}</" + mt_prefix + "ArchiveListHeader>"),
            (mt_prefix + "ArchiveNext\tMT[B]", mt_prefix + "ArchiveNext${1}>${2:Contents}</" + mt_prefix + "ArchiveNext>"),
            (mt_prefix + "ArchivePrevious\tMT[B]", mt_prefix + "ArchivePrevious${1}>${2:Contents}</" + mt_prefix + "ArchivePrevious>"),
            (mt_prefix + "Archives\tMT[B]", mt_prefix + "Archives${1}>${2:Contents}</" + mt_prefix + "Archives>"),
            (mt_prefix + "Asset\tMT[B]", mt_prefix + "Asset${1}>${2:Contents}</" + mt_prefix + "Asset>"),
            (mt_prefix + "AssetIsFirstInRow\tMT[B]", mt_prefix + "AssetIsFirstInRow${1}>${2:Contents}</" + mt_prefix + "AssetIsFirstInRow>"),
            (mt_prefix + "AssetIsLastInRow\tMT[B]", mt_prefix + "AssetIsLastInRow${1}>${2:Contents}</" + mt_prefix + "AssetIsLastInRow>"),
            (mt_prefix + "Assets\tMT[B]", mt_prefix + "Assets${1}>${2:Contents}</" + mt_prefix + "Assets>"),
            (mt_prefix + "AssetsFooter\tMT[B]", mt_prefix + "AssetsFooter${1}>${2:Contents}</" + mt_prefix + "AssetsFooter>"),
            (mt_prefix + "AssetsHeader\tMT[B]", mt_prefix + "AssetsHeader${1}>${2:Contents}</" + mt_prefix + "AssetsHeader>"),
            (mt_prefix + "AssetTags\tMT[B]", mt_prefix + "AssetTags${1}>${2:Contents}</" + mt_prefix + "AssetTags>"),
            (mt_prefix + "AudioCustomFields\tMT[B]", mt_prefix + "AudioCustomFields${1}>${2:Contents}</" + mt_prefix + "AudioCustomFields>"),
            (mt_prefix + "AuthorCommentResponses\tMT[B]", mt_prefix + "AuthorCommentResponses${1}>${2:Contents}</" + mt_prefix + "AuthorCommentResponses>"),
            (mt_prefix + "AuthorComments\tMT[B]", mt_prefix + "AuthorComments${1}>${2:Contents}</" + mt_prefix + "AuthorComments>"),
            (mt_prefix + "AuthorCustomFields\tMT[B]", mt_prefix + "AuthorCustomFields${1}>${2:Contents}</" + mt_prefix + "AuthorCustomFields>"),
            (mt_prefix + "AuthorFollowers\tMT[B]", mt_prefix + "AuthorFollowers${1}>${2:Contents}</" + mt_prefix + "AuthorFollowers>"),
            (mt_prefix + "AuthorFollowing\tMT[B]", mt_prefix + "AuthorFollowing${1}>${2:Contents}</" + mt_prefix + "AuthorFollowing>"),
            (mt_prefix + "AuthorFollowingComments\tMT[B]", mt_prefix + "AuthorFollowingComments${1}>${2:Contents}</" + mt_prefix + "AuthorFollowingComments>"),
            (mt_prefix + "AuthorFollowingEntries\tMT[B]", mt_prefix + "AuthorFollowingEntries${1}>${2:Contents}</" + mt_prefix + "AuthorFollowingEntries>"),
            (mt_prefix + "AuthorFollowingFavorites\tMT[B]", mt_prefix + "AuthorFollowingFavorites${1}>${2:Contents}</" + mt_prefix + "AuthorFollowingFavorites>"),
            (mt_prefix + "AuthorHasEntry\tMT[B]", mt_prefix + "AuthorHasEntry${1}>${2:Contents}</" + mt_prefix + "AuthorHasEntry>"),
            (mt_prefix + "AuthorHasPage\tMT[B]", mt_prefix + "AuthorHasPage${1}>${2:Contents}</" + mt_prefix + "AuthorHasPage>"),
            (mt_prefix + "AuthorNext\tMT[B]", mt_prefix + "AuthorNext${1}>${2:Contents}</" + mt_prefix + "AuthorNext>"),
            (mt_prefix + "AuthorPrevious\tMT[B]", mt_prefix + "AuthorPrevious${1}>${2:Contents}</" + mt_prefix + "AuthorPrevious>"),
            (mt_prefix + "Authors\tMT[B]", mt_prefix + "Authors${1}>${2:Contents}</" + mt_prefix + "Authors>"),
            (mt_prefix + "AuthorUserpicAsset\tMT[B]", mt_prefix + "AuthorUserpicAsset${1}>${2:Contents}</" + mt_prefix + "AuthorUserpicAsset>"),
            (mt_prefix + "BlogCustomFields\tMT[B]", mt_prefix + "BlogCustomFields${1}>${2:Contents}</" + mt_prefix + "BlogCustomFields>"),
            (mt_prefix + "BlogParentWebsite\tMT[B]", mt_prefix + "BlogParentWebsite${1}>${2:Contents}</" + mt_prefix + "BlogParentWebsite>"),
            (mt_prefix + "BlogResultFooter\tMT[B]", mt_prefix + "BlogResultFooter${1}>${2:Contents}</" + mt_prefix + "BlogResultFooter>"),
            (mt_prefix + "BlogResultHeader\tMT[B]", mt_prefix + "BlogResultHeader${1}>${2:Contents}</" + mt_prefix + "BlogResultHeader>"),
            (mt_prefix + "Blogs\tMT[B]", mt_prefix + "Blogs${1}>${2:Contents}</" + mt_prefix + "Blogs>"),
            (mt_prefix + "BuildRecurs\tDynamicMTML[B]", mt_prefix + "BuildRecurs${1}>${2}</" + mt_prefix + "BuildRecurs>"),
            (mt_prefix + "Calendar\tMT[B]", mt_prefix + "Calendar${1}>${2:Contents}</" + mt_prefix + "Calendar>"),
            (mt_prefix + "CalendarWeekFooter\tMT[B]", mt_prefix + "CalendarWeekFooter${1}>${2:Contents}</" + mt_prefix + "CalendarWeekFooter>"),
            (mt_prefix + "CalendarWeekHeader\tMT[B]", mt_prefix + "CalendarWeekHeader${1}>${2:Contents}</" + mt_prefix + "CalendarWeekHeader>"),
            (mt_prefix + "Categories\tMT[B]", mt_prefix + "Categories${1}>${2:Contents}</" + mt_prefix + "Categories>"),
            (mt_prefix + "CategoryCustomFields\tMT[B]", mt_prefix + "CategoryCustomFields${1}>${2:Contents}</" + mt_prefix + "CategoryCustomFields>"),
            (mt_prefix + "CategoryNext\tMT[B]", mt_prefix + "CategoryNext${1}>${2:Contents}</" + mt_prefix + "CategoryNext>"),
            (mt_prefix + "CategoryPrevious\tMT[B]", mt_prefix + "CategoryPrevious${1}>${2:Contents}</" + mt_prefix + "CategoryPrevious>"),
            (mt_prefix + "ClientAuthorBlock\tDynamicMTML[B]", mt_prefix + "ClientAuthorBlock${1}>${2}</" + mt_prefix + "ClientAuthorBlock>"),
            (mt_prefix + "CommentCustomFields\tMT[B]", mt_prefix + "CommentCustomFields${1}>${2:Contents}</" + mt_prefix + "CommentCustomFields>"),
            (mt_prefix + "CommentEntry\tMT[B]", mt_prefix + "CommentEntry${1}>${2:Contents}</" + mt_prefix + "CommentEntry>"),
            (mt_prefix + "CommenterUserpicAsset\tMT[B]", mt_prefix + "CommenterUserpicAsset${1}>${2:Contents}</" + mt_prefix + "CommenterUserpicAsset>"),
            (mt_prefix + "CommentOut\tDynamicMTML[B]", mt_prefix + "CommentOut${1}>${2}</" + mt_prefix + "CommentOut>"),
            (mt_prefix + "CommentParent\tMT[B]", mt_prefix + "CommentParent${1}>${2:Contents}</" + mt_prefix + "CommentParent>"),
            (mt_prefix + "CommentReplies\tMT[B]", mt_prefix + "CommentReplies${1}>${2:Contents}</" + mt_prefix + "CommentReplies>"),
            (mt_prefix + "Comments\tMT[B]", mt_prefix + "Comments${1}>${2:Contents}</" + mt_prefix + "Comments>"),
            (mt_prefix + "CommentsFooter\tMT[B]", mt_prefix + "CommentsFooter${1}>${2:Contents}</" + mt_prefix + "CommentsFooter>"),
            (mt_prefix + "CommentsHeader\tMT[B]", mt_prefix + "CommentsHeader${1}>${2:Contents}</" + mt_prefix + "CommentsHeader>"),
            (mt_prefix + "CommentStrip\tDynamicMTML[B]", mt_prefix + "CommentStrip${1}>${2}</" + mt_prefix + "CommentStrip>"),
            (mt_prefix + "CustomFieldIsRequired\tMT[B]", mt_prefix + "CustomFieldIsRequired${1}>${2:Contents}</" + mt_prefix + "CustomFieldIsRequired>"),
            (mt_prefix + "DateFooter\tMT[B]", mt_prefix + "DateFooter${1}>${2:Contents}</" + mt_prefix + "DateFooter>"),
            (mt_prefix + "DateHeader\tMT[B]", mt_prefix + "DateHeader${1}>${2:Contents}</" + mt_prefix + "DateHeader>"),
            (mt_prefix + "DynamicMTML\tDynamicMTML[B]", mt_prefix + "DynamicMTML>${1}</" + mt_prefix + "DynamicMTML>"),
            (mt_prefix + "Else\tMT[B]", mt_prefix + "Else${1}>${2:Contents}</" + mt_prefix + "Else>"),
            (mt_prefix + "Entries\tMT[B]", mt_prefix + "Entries${1}>${2:Contents}</" + mt_prefix + "Entries>"),
            (mt_prefix + "EntriesFooter\tMT[B]", mt_prefix + "EntriesFooter${1}>${2:Contents}</" + mt_prefix + "EntriesFooter>"),
            (mt_prefix + "EntriesHeader\tMT[B]", mt_prefix + "EntriesHeader${1}>${2:Contents}</" + mt_prefix + "EntriesHeader>"),
            (mt_prefix + "EntriesWithSubCategories\tMT[B]", mt_prefix + "EntriesWithSubCategories${1}>${2:Contents}</" + mt_prefix + "EntriesWithSubCategories>"),
            (mt_prefix + "EntryAdditionalCategories\tMT[B]", mt_prefix + "EntryAdditionalCategories${1}>${2:Contents}</" + mt_prefix + "EntryAdditionalCategories>"),
            (mt_prefix + "EntryAssets\tMT[B]", mt_prefix + "EntryAssets${1}>${2:Contents}</" + mt_prefix + "EntryAssets>"),
            (mt_prefix + "EntryAuthorUserpicAsset\tMT[B]", mt_prefix + "EntryAuthorUserpicAsset${1}>${2:Contents}</" + mt_prefix + "EntryAuthorUserpicAsset>"),
            (mt_prefix + "EntryCategories\tMT[B]", mt_prefix + "EntryCategories${1}>${2:Contents}</" + mt_prefix + "EntryCategories>"),
            (mt_prefix + "EntryCategoryBlock\tDynamicMTML[B]", mt_prefix + "EntryCategoryBlock${1}>${2}</" + mt_prefix + "EntryCategoryBlock>"),
            (mt_prefix + "EntryCustomFields\tMT[B]", mt_prefix + "EntryCustomFields${1}>${2:Contents}</" + mt_prefix + "EntryCustomFields>"),
            (mt_prefix + "EntryNext\tMT[B]", mt_prefix + "EntryNext${1}>${2:Contents}</" + mt_prefix + "EntryNext>"),
            (mt_prefix + "EntryPrevious\tMT[B]", mt_prefix + "EntryPrevious${1}>${2:Contents}</" + mt_prefix + "EntryPrevious>"),
            (mt_prefix + "EntryPrimaryCategory\tMT[B]", mt_prefix + "EntryPrimaryCategory${1}>${2:Contents}</" + mt_prefix + "EntryPrimaryCategory>"),
            (mt_prefix + "EntryTags\tMT[B]", mt_prefix + "EntryTags${1}>${2:Contents}</" + mt_prefix + "EntryTags>"),
            (mt_prefix + "Feed\tMT[B]", mt_prefix + "Feed${1}>${2:Contents}</" + mt_prefix + "Feed>"),
            (mt_prefix + "FeedEntries\tMT[B]", mt_prefix + "FeedEntries${1}>${2:Contents}</" + mt_prefix + "FeedEntries>"),
            (mt_prefix + "FileCustomFields\tMT[B]", mt_prefix + "FileCustomFields${1}>${2:Contents}</" + mt_prefix + "FileCustomFields>"),
            (mt_prefix + "FolderCustomFields\tMT[B]", mt_prefix + "FolderCustomFields${1}>${2:Contents}</" + mt_prefix + "FolderCustomFields>"),
            (mt_prefix + "FolderFooter\tMT[B]", mt_prefix + "FolderFooter${1}>${2:Contents}</" + mt_prefix + "FolderFooter>"),
            (mt_prefix + "FolderHeader\tMT[B]", mt_prefix + "FolderHeader${1}>${2:Contents}</" + mt_prefix + "FolderHeader>"),
            (mt_prefix + "FolderNext\tMT[B]", mt_prefix + "FolderNext${1}>${2:Contents}</" + mt_prefix + "FolderNext>"),
            (mt_prefix + "FolderPrevious\tMT[B]", mt_prefix + "FolderPrevious${1}>${2:Contents}</" + mt_prefix + "FolderPrevious>"),
            (mt_prefix + "Folders\tMT[B]", mt_prefix + "Folders${1}>${2:Contents}</" + mt_prefix + "Folders>"),
            (mt_prefix + "For\tMT[B]", mt_prefix + "For var=\"${1:i}\" from=\"${2}\" to=\"${3}\"${4: glue=\"\"}>${5:Contents}</" + mt_prefix + "For>"),
            (mt_prefix + "HasNoParentCategory\tMT[B]", mt_prefix + "HasNoParentCategory${1}>${2:Contents}</" + mt_prefix + "HasNoParentCategory>"),
            (mt_prefix + "HasNoSubCategories\tMT[B]", mt_prefix + "HasNoSubCategories${1}>${2:Contents}</" + mt_prefix + "HasNoSubCategories>"),
            (mt_prefix + "HasParentCategory\tMT[B]", mt_prefix + "HasParentCategory${1}>${2:Contents}</" + mt_prefix + "HasParentCategory>"),
            (mt_prefix + "HasParentFolder\tMT[B]", mt_prefix + "HasParentFolder${1}>${2:Contents}</" + mt_prefix + "HasParentFolder>"),
            (mt_prefix + "HasSubCategories\tMT[B]", mt_prefix + "HasSubCategories${1}>${2:Contents}</" + mt_prefix + "HasSubCategories>"),
            (mt_prefix + "HasSubFolders\tMT[B]", mt_prefix + "HasSubFolders${1}>${2:Contents}</" + mt_prefix + "HasSubFolders>"),
            (mt_prefix + "Ignore\tMT[B]", mt_prefix + "Ignore>${1}</" + mt_prefix + "Ignore>"),
            (mt_prefix + "ImageCustomFields\tMT[B]", mt_prefix + "ImageCustomFields${1}>${2:Contents}</" + mt_prefix + "ImageCustomFields>"),
            (mt_prefix + "IncludeBlock\tMT[B]", mt_prefix + "IncludeBlock${1}>${2:Contents}</" + mt_prefix + "IncludeBlock>"),
            (mt_prefix + "IndexList\tMT[B]", mt_prefix + "IndexList${1}>${2:Contents}</" + mt_prefix + "IndexList>"),
            (mt_prefix + "LoginAuthorCtx\tDynamicMTML[B]", mt_prefix + "LoginAuthorCtx${1}>${2}</" + mt_prefix + "LoginAuthorCtx>"),
            (mt_prefix + "Loop\tMT[B]", mt_prefix + "Loop name=\"${1:VariableName}\"${2: sort_by=\"\"}${3: glue=\"\"}>${4:Contents}</" + mt_prefix + "Loop>"),
            (mt_prefix + "MarkdownOptions\tMT[B]", mt_prefix + "MarkdownOptions${1}>${2:Contents}</" + mt_prefix + "MarkdownOptions>"),
            (mt_prefix + "MultiBlog\tMT[B]", mt_prefix + "MultiBlog${1}>${2:Contents}</" + mt_prefix + "MultiBlog>"),
            (mt_prefix + "MultiBlogLocalBlog\tMT[B]", mt_prefix + "MultiBlogLocalBlog${1}>${2:Contents}</" + mt_prefix + "MultiBlogLocalBlog>"),
            (mt_prefix + "NonDynamicMTML\tDynamicMTML[B]", mt_prefix + "NonDynamicMTML${1}>${2}</" + mt_prefix + "NonDynamicMTML>"),
            (mt_prefix + "NoSearch\tMT[B]", mt_prefix + "NoSearch${1}>${2:Contents}</" + mt_prefix + "NoSearch>"),
            (mt_prefix + "NoSearchResults\tMT[B]", mt_prefix + "NoSearchResults${1}>${2:Contents}</" + mt_prefix + "NoSearchResults>"),
            (mt_prefix + "OtherBlog\tMT[B]", mt_prefix + "OtherBlog${1}>${2:Contents}</" + mt_prefix + "OtherBlog>"),
            (mt_prefix + "OtherProfiles\tMT[B]", mt_prefix + "OtherProfiles${1}>${2:Contents}</" + mt_prefix + "OtherProfiles>"),
            (mt_prefix + "PageAssets\tMT[B]", mt_prefix + "PageAssets${1}>${2:Contents}</" + mt_prefix + "PageAssets>"),
            (mt_prefix + "PageCustomFields\tMT[B]", mt_prefix + "PageCustomFields${1}>${2:Contents}</" + mt_prefix + "PageCustomFields>"),
            (mt_prefix + "PageFolder\tMT[B]", mt_prefix + "PageFolder${1}>${2:Contents}</" + mt_prefix + "PageFolder>"),
            (mt_prefix + "PageNext\tMT[B]", mt_prefix + "PageNext${1}>${2:Contents}</" + mt_prefix + "PageNext>"),
            (mt_prefix + "PagePrevious\tMT[B]", mt_prefix + "PagePrevious${1}>${2:Contents}</" + mt_prefix + "PagePrevious>"),
            (mt_prefix + "PagerBlock\tMT[B]", mt_prefix + "PagerBlock${1}>${2:Contents}</" + mt_prefix + "PagerBlock>"),
            (mt_prefix + "Pages\tMT[B]", mt_prefix + "Pages${1}>${2:Contents}</" + mt_prefix + "Pages>"),
            (mt_prefix + "PagesFooter\tMT[B]", mt_prefix + "PagesFooter${1}>${2:Contents}</" + mt_prefix + "PagesFooter>"),
            (mt_prefix + "PagesHeader\tMT[B]", mt_prefix + "PagesHeader${1}>${2:Contents}</" + mt_prefix + "PagesHeader>"),
            (mt_prefix + "PageTags\tMT[B]", mt_prefix + "PageTags${1}>${2:Contents}</" + mt_prefix + "PageTags>"),
            (mt_prefix + "ParentCategories\tMT[B]", mt_prefix + "ParentCategories${1}>${2:Contents}</" + mt_prefix + "ParentCategories>"),
            (mt_prefix + "ParentCategory\tMT[B]", mt_prefix + "ParentCategory${1}>${2:Contents}</" + mt_prefix + "ParentCategory>"),
            (mt_prefix + "ParentFolder\tMT[B]", mt_prefix + "ParentFolder${1}>${2:Contents}</" + mt_prefix + "ParentFolder>"),
            (mt_prefix + "ParentFolders\tMT[B]", mt_prefix + "ParentFolders${1}>${2:Contents}</" + mt_prefix + "ParentFolders>"),
            (mt_prefix + "PasswordValidation\tMT[B]", mt_prefix + "PasswordValidation${1}>${2:Contents}</" + mt_prefix + "PasswordValidation>"),
            (mt_prefix + "PasswordValidationRule\tMT[B]", mt_prefix + "PasswordValidationRule${1}>${2:Contents}</" + mt_prefix + "PasswordValidationRule>"),
            (mt_prefix + "PingEntry\tMT[B]", mt_prefix + "PingEntry${1}>${2:Contents}</" + mt_prefix + "PingEntry>"),
            (mt_prefix + "Pings\tMT[B]", mt_prefix + "Pings${1}>${2:Contents}</" + mt_prefix + "Pings>"),
            (mt_prefix + "PingsFooter\tMT[B]", mt_prefix + "PingsFooter${1}>${2:Contents}</" + mt_prefix + "PingsFooter>"),
            (mt_prefix + "PingsHeader\tMT[B]", mt_prefix + "PingsHeader${1}>${2:Contents}</" + mt_prefix + "PingsHeader>"),
            (mt_prefix + "PingsSent\tMT[B]", mt_prefix + "PingsSent${1}>${2:Contents}</" + mt_prefix + "PingsSent>"),
            (mt_prefix + "ProfileServices\tMT[B]", mt_prefix + "ProfileServices${1}>${2:Contents}</" + mt_prefix + "ProfileServices>"),
            (mt_prefix + "QueryLoop\tDynamicMTML[B]", mt_prefix + "QueryLoop${1}>${2}</" + mt_prefix + "QueryLoop>"),
            (mt_prefix + "QueryVars\tDynamicMTML[B]", mt_prefix + "QueryVars${1}>${2}</" + mt_prefix + "QueryVars>"),
            (mt_prefix + "RawMTML\tDynamicMTML[B]", mt_prefix + "RawMTML${1}>${2}</" + mt_prefix + "RawMTML>"),
            (mt_prefix + "ReferralKeywords\tDynamicMTML[B]", mt_prefix + "ReferralKeywords${1}>${2}</" + mt_prefix + "ReferralKeywords>"),
            (mt_prefix + "SearchEntries\tDynamicMTML[B]", mt_prefix + "SearchEntries${1}>${2}</" + mt_prefix + "SearchEntries>"),
            (mt_prefix + "SearchResults\tMT[B]", mt_prefix + "SearchResults${1}>${2:Contents}</" + mt_prefix + "SearchResults>"),
            (mt_prefix + "SearchResultsFooter\tMT[B]", mt_prefix + "SearchResultsFooter${1}>${2:Contents}</" + mt_prefix + "SearchResultsFooter>"),
            (mt_prefix + "SearchResultsHeader\tMT[B]", mt_prefix + "SearchResultsHeader${1}>${2:Contents}</" + mt_prefix + "SearchResultsHeader>"),
            (mt_prefix + "Section\tMT[B]", mt_prefix + "Section${1}>${2:Contents}</" + mt_prefix + "Section>"),
            (mt_prefix + "SetHashVar\tMT[B]", mt_prefix + "SetHashVar${1}>${2:Contents}</" + mt_prefix + "SetHashVar>"),
            (mt_prefix + "SetQueryVars\tDynamicMTML[B]", mt_prefix + "SetQueryVars${1}>${2}</" + mt_prefix + "SetQueryVars>"),
            (mt_prefix + "SetVarBlock\tMT[B]", mt_prefix + "SetVarBlock name=\"${1:VariableName}\">${2:Contents}</" + mt_prefix + "SetVarBlock>"),
            (mt_prefix + "SetVars\tMT[B]", mt_prefix + "SetVars>\n${1:Variable Name}=${2:Value}\n</" + mt_prefix + "SetVars>"),
            (mt_prefix + "SetVarTemplate\tMT[B]", mt_prefix + "SetVarTemplate name=\"${1:Variable Name}\">${2:Contents}</" + mt_prefix + "SetVarTemplate>"),
            (mt_prefix + "SplitVars\tDynamicMTML[B]", mt_prefix + "SplitVars${1}>${2}</" + mt_prefix + "SplitVars>"),
            (mt_prefix + "StreamActionRollup\tMT[B]", mt_prefix + "StreamActionRollup${1}>${2:Contents}</" + mt_prefix + "StreamActionRollup>"),
            (mt_prefix + "StreamActionTags\tMT[B]", mt_prefix + "StreamActionTags${1}>${2:Contents}</" + mt_prefix + "StreamActionTags>"),
            (mt_prefix + "SubCategories\tMT[B]", mt_prefix + "SubCategories${1}>${2:Contents}</" + mt_prefix + "SubCategories>"),
            (mt_prefix + "SubCatIsFirst\tMT[B]", mt_prefix + "SubCatIsFirst${1}>${2:Contents}</" + mt_prefix + "SubCatIsFirst>"),
            (mt_prefix + "SubCatIsLast\tMT[B]", mt_prefix + "SubCatIsLast${1}>${2:Contents}</" + mt_prefix + "SubCatIsLast>"),
            (mt_prefix + "SubFolders\tMT[B]", mt_prefix + "SubFolders${1}>${2:Contents}</" + mt_prefix + "SubFolders>"),
            (mt_prefix + "Tags\tMT[B]", mt_prefix + "Tags${1}>${2:Contents}</" + mt_prefix + "Tags>"),
            (mt_prefix + "TemplateCustomFields\tMT[B]", mt_prefix + "TemplateCustomFields${1}>${2:Contents}</" + mt_prefix + "TemplateCustomFields>"),
            (mt_prefix + "Textile\tMT[B]", mt_prefix + "Textile${1}>${2:Contents}</" + mt_prefix + "Textile>"),
            (mt_prefix + "TopLevelCategories\tMT[B]", mt_prefix + "TopLevelCategories${1}>${2:Contents}</" + mt_prefix + "TopLevelCategories>"),
            (mt_prefix + "TopLevelFolder\tMT[B]", mt_prefix + "TopLevelFolder${1}>${2:Contents}</" + mt_prefix + "TopLevelFolder>"),
            (mt_prefix + "TopLevelFolders\tMT[B]", mt_prefix + "TopLevelFolders${1}>${2:Contents}</" + mt_prefix + "TopLevelFolders>"),
            (mt_prefix + "TopLevelParent\tMT[B]", mt_prefix + "TopLevelParent${1}>${2:Contents}</" + mt_prefix + "TopLevelParent>"),
            (mt_prefix + "Unless\tMT[B]", mt_prefix + "Unless name=\"${1:VariableName}\">${2:Contents}</" + mt_prefix + "Unless>"),
            (mt_prefix + "VideoCustomFields\tMT[B]", mt_prefix + "VideoCustomFields${1}>${2:Contents}</" + mt_prefix + "VideoCustomFields>"),
            (mt_prefix + "WebsiteCustomFields\tMT[B]", mt_prefix + "WebsiteCustomFields${1}>${2:Contents}</" + mt_prefix + "WebsiteCustomFields>"),
            (mt_prefix + "WebsiteHasBlog\tMT[B]", mt_prefix + "WebsiteHasBlog${1}>${2:Contents}</" + mt_prefix + "WebsiteHasBlog>"),
            (mt_prefix + "Websites\tMT[B]", mt_prefix + "Websites${1}>${2:Contents}</" + mt_prefix + "Websites>"),
            ("mtapp:Form\tMT[B]", "mtapp:Form${1}>${2:Contents}</mtapp:Form>"),
            ("mtapp:Listing\tMT[B]", "mtapp:Listing${1}>${2:Contents}</mtapp:Listing>"),
            ("mtapp:Setting\tMT[B]", "mtapp:Setting${1}>${2:Contents}</mtapp:Setting>"),
            ("mtapp:SettingGroup\tMT[B]", "mtapp:SettingGroup${1}>${2:Contents}</mtapp:SettingGroup>"),
            ("mtapp:StatusMsg\tMT[B]", "mtapp:StatusMsg${1}>${2:Contents}</mtapp:StatusMsg>"),
            ("mtapp:Widget\tMT[B]", "mtapp:Widget${1}>${2:Contents}</mtapp:Widget>"),
            # Conditional Tag
            (mt_prefix + "AssetIfTagged\tMT[C]", mt_prefix + "AssetIfTagged${1}>${2:Contents}</" + mt_prefix + "AssetIfTagged>"),
            (mt_prefix + "AuthorIfFollowed\tMT[C]", mt_prefix + "AuthorIfFollowed${1}>${2:Contents}</" + mt_prefix + "AuthorIfFollowed>"),
            (mt_prefix + "AuthorIfFollowing\tMT[C]", mt_prefix + "AuthorIfFollowing${1}>${2:Contents}</" + mt_prefix + "AuthorIfFollowing>"),
            (mt_prefix + "BlogIfCCLicense\tMT[C]", mt_prefix + "BlogIfCCLicense${1}>${2:Contents}</" + mt_prefix + "BlogIfCCLicense>"),
            (mt_prefix + "BlogIfCommentsOpen\tMT[C]", mt_prefix + "BlogIfCommentsOpen${1}>${2:Contents}</" + mt_prefix + "BlogIfCommentsOpen>"),
            (mt_prefix + "CalendarIfBlank\tMT[C]", mt_prefix + "CalendarIfBlank${1}>${2:Contents}</" + mt_prefix + "CalendarIfBlank>"),
            (mt_prefix + "CalendarIfEntries\tMT[C]", mt_prefix + "CalendarIfEntries${1}>${2:Contents}</" + mt_prefix + "CalendarIfEntries>"),
            (mt_prefix + "CalendarIfNoEntries\tMT[C]", mt_prefix + "CalendarIfNoEntries${1}>${2:Contents}</" + mt_prefix + "CalendarIfNoEntries>"),
            (mt_prefix + "CalendarIfToday\tMT[C]", mt_prefix + "CalendarIfToday${1}>${2:Contents}</" + mt_prefix + "CalendarIfToday>"),
            (mt_prefix + "CategoryIfAllowPings\tMT[C]", mt_prefix + "CategoryIfAllowPings${1}>${2:Contents}</" + mt_prefix + "CategoryIfAllowPings>"),
            (mt_prefix + "CommenterIfTrusted\tMT[C]", mt_prefix + "CommenterIfTrusted${1}>${2:Contents}</" + mt_prefix + "CommenterIfTrusted>"),
            (mt_prefix + "CommentIfModerated\tMT[C]", mt_prefix + "CommentIfModerated${1}>${2:Contents}</" + mt_prefix + "CommentIfModerated>"),
            (mt_prefix + "ElseIf\tMT[C]", mt_prefix + "ElseIf${1}>${2:Contents}</" + mt_prefix + "ElseIf>"),
            (mt_prefix + "EntryIfAllowComments\tMT[C]", mt_prefix + "EntryIfAllowComments${1}>${2:Contents}</" + mt_prefix + "EntryIfAllowComments>"),
            (mt_prefix + "EntryIfAllowPings\tMT[C]", mt_prefix + "EntryIfAllowPings${1}>${2:Contents}</" + mt_prefix + "EntryIfAllowPings>"),
            (mt_prefix + "EntryIfCategory\tMT[C]", mt_prefix + "EntryIfCategory${1}>${2:Contents}</" + mt_prefix + "EntryIfCategory>"),
            (mt_prefix + "EntryIfCommentsOpen\tMT[C]", mt_prefix + "EntryIfCommentsOpen${1}>${2:Contents}</" + mt_prefix + "EntryIfCommentsOpen>"),
            (mt_prefix + "EntryIfExtended\tMT[C]", mt_prefix + "EntryIfExtended${1}>${2:Contents}</" + mt_prefix + "EntryIfExtended>"),
            (mt_prefix + "EntryIfTagged\tMT[C]", mt_prefix + "EntryIfTagged${1}>${2:Contents}</" + mt_prefix + "EntryIfTagged>"),
            (mt_prefix + "If\tMT[C]", mt_prefix + "If name=\"${1:VariableName}\">${2:Contents}</" + mt_prefix + "If>"),
            (mt_prefix + "If else\tMT[C]", mt_prefix + "If name=\"${1:VarName}\">${2:True Contents}<mt:Else>${3:False Contents}</" + mt_prefix + "If>"),
            (mt_prefix + "If tag\tMT[C]", mt_prefix + "If tag=\"${1:TagName}\">${2:Contents}</" + mt_prefix + "If>"),
            (mt_prefix + "If tag else\tMT[C]", mt_prefix + "If tag=\"${1:TagName}\">${2:True Contents}<mt:Else>${3:False Contents}</" + mt_prefix + "If>"),
            (mt_prefix + "IfAllowCommentHTML\tMT[C]", mt_prefix + "IfAllowCommentHTML${1}>${2:Contents}</" + mt_prefix + "IfAllowCommentHTML>"),
            (mt_prefix + "IfAnonymousRecommendAllowed\tMT[C]", mt_prefix + "IfAnonymousRecommendAllowed${1}>${2:Contents}</" + mt_prefix + "IfAnonymousRecommendAllowed>"),
            (mt_prefix + "IfArchiveType\tMT[C]", mt_prefix + "IfArchiveType${1}>${2:Contents}</" + mt_prefix + "IfArchiveType>"),
            (mt_prefix + "IfArchiveTypeEnabled\tMT[C]", mt_prefix + "IfArchiveTypeEnabled${1}>${2:Contents}</" + mt_prefix + "IfArchiveTypeEnabled>"),
            (mt_prefix + "IfBlog\tMT[C]", mt_prefix + "IfBlog${1}>${2:Contents}</" + mt_prefix + "IfBlog>"),
            (mt_prefix + "IfCategory\tMT[C]", mt_prefix + "IfCategory${1}>${2:Contents}</" + mt_prefix + "IfCategory>"),
            (mt_prefix + "IfCommenterIsAuthor\tMT[C]", mt_prefix + "IfCommenterIsAuthor${1}>${2:Contents}</" + mt_prefix + "IfCommenterIsAuthor>"),
            (mt_prefix + "IfCommenterIsEntryAuthor\tMT[C]", mt_prefix + "IfCommenterIsEntryAuthor${1}>${2:Contents}</" + mt_prefix + "IfCommenterIsEntryAuthor>"),
            (mt_prefix + "IfCommenterTrusted\tMT[C]", mt_prefix + "IfCommenterTrusted${1}>${2:Contents}</" + mt_prefix + "IfCommenterTrusted>"),
            (mt_prefix + "IfCommentParent\tMT[C]", mt_prefix + "IfCommentParent${1}>${2:Contents}</" + mt_prefix + "IfCommentParent>"),
            (mt_prefix + "IfCommentReplies\tMT[C]", mt_prefix + "IfCommentReplies${1}>${2:Contents}</" + mt_prefix + "IfCommentReplies>"),
            (mt_prefix + "IfCommentsAccepted\tMT[C]", mt_prefix + "IfCommentsAccepted${1}>${2:Contents}</" + mt_prefix + "IfCommentsAccepted>"),
            (mt_prefix + "IfCommentsActive\tMT[C]", mt_prefix + "IfCommentsActive${1}>${2:Contents}</" + mt_prefix + "IfCommentsActive>"),
            (mt_prefix + "IfCommentsAllowed\tMT[C]", mt_prefix + "IfCommentsAllowed${1}>${2:Contents}</" + mt_prefix + "IfCommentsAllowed>"),
            (mt_prefix + "IfCommentsModerated\tMT[C]", mt_prefix + "IfCommentsModerated${1}>${2:Contents}</" + mt_prefix + "IfCommentsModerated>"),
            (mt_prefix + "IfCurrentPage\tMT[C]", mt_prefix + "IfCurrentPage${1}>${2:Contents}</" + mt_prefix + "IfCurrentPage>"),
            (mt_prefix + "IfDynamic\tMT[C]", mt_prefix + "IfDynamic${1}>${2:Contents}</" + mt_prefix + "IfDynamic>"),
            (mt_prefix + "IfFolder\tMT[C]", mt_prefix + "IfFolder${1}>${2:Contents}</" + mt_prefix + "IfFolder>"),
            (mt_prefix + "IfImageSupport\tMT[C]", mt_prefix + "IfImageSupport${1}>${2:Contents}</" + mt_prefix + "IfImageSupport>"),
            (mt_prefix + "IfIsAncestor\tMT[C]", mt_prefix + "IfIsAncestor${1}>${2:Contents}</" + mt_prefix + "IfIsAncestor>"),
            (mt_prefix + "IfIsDescendant\tMT[C]", mt_prefix + "IfIsDescendant${1}>${2:Contents}</" + mt_prefix + "IfIsDescendant>"),
            (mt_prefix + "IfLoggedIn\tMT[C]", mt_prefix + "IfLoggedIn${1}>${2:Contents}</" + mt_prefix + "IfLoggedIn>"),
            (mt_prefix + "IfLogin\tDynamicMTML[C]", mt_prefix + "IfLogin${1}>${2}</" + mt_prefix + "IfLogin>"),
            (mt_prefix + "IfMaxResultsCutoff\tMT[C]", mt_prefix + "IfMaxResultsCutoff${1}>${2:Contents}</" + mt_prefix + "IfMaxResultsCutoff>"),
            (mt_prefix + "IfMoreResults\tMT[C]", mt_prefix + "IfMoreResults${1}>${2:Contents}</" + mt_prefix + "IfMoreResults>"),
            (mt_prefix + "IfNeedEmail\tMT[C]", mt_prefix + "IfNeedEmail${1}>${2:Contents}</" + mt_prefix + "IfNeedEmail>"),
            (mt_prefix + "IfNonEmpty\tMT[C]", mt_prefix + "IfNonEmpty${1}>${2:Contents}</" + mt_prefix + "IfNonEmpty>"),
            (mt_prefix + "IfNonZero\tMT[C]", mt_prefix + "IfNonZero${1}>${2:Contents}</" + mt_prefix + "IfNonZero>"),
            (mt_prefix + "IfPingsAccepted\tMT[C]", mt_prefix + "IfPingsAccepted${1}>${2:Contents}</" + mt_prefix + "IfPingsAccepted>"),
            (mt_prefix + "IfPingsActive\tMT[C]", mt_prefix + "IfPingsActive${1}>${2:Contents}</" + mt_prefix + "IfPingsActive>"),
            (mt_prefix + "IfPingsAllowed\tMT[C]", mt_prefix + "IfPingsAllowed${1}>${2:Contents}</" + mt_prefix + "IfPingsAllowed>"),
            (mt_prefix + "IfPingsModerated\tMT[C]", mt_prefix + "IfPingsModerated${1}>${2:Contents}</" + mt_prefix + "IfPingsModerated>"),
            (mt_prefix + "IfPreviousResults\tMT[C]", mt_prefix + "IfPreviousResults${1}>${2:Contents}</" + mt_prefix + "IfPreviousResults>"),
            (mt_prefix + "IfRegistrationAllowed\tMT[C]", mt_prefix + "IfRegistrationAllowed${1}>${2:Contents}</" + mt_prefix + "IfRegistrationAllowed>"),
            (mt_prefix + "IfRegistrationNotRequired\tMT[C]", mt_prefix + "IfRegistrationNotRequired${1}>${2:Contents}</" + mt_prefix + "IfRegistrationNotRequired>"),
            (mt_prefix + "IfRegistrationRequired\tMT[C]", mt_prefix + "IfRegistrationRequired${1}>${2:Contents}</" + mt_prefix + "IfRegistrationRequired>"),
            (mt_prefix + "IfRequireCommentEmails\tMT[C]", mt_prefix + "IfRequireCommentEmails${1}>${2:Contents}</" + mt_prefix + "IfRequireCommentEmails>"),
            (mt_prefix + "IfStatic\tMT[C]", mt_prefix + "IfStatic${1}>${2:Contents}</" + mt_prefix + "IfStatic>"),
            (mt_prefix + "IfStraightSearch\tMT[C]", mt_prefix + "IfStraightSearch${1}>${2:Contents}</" + mt_prefix + "IfStraightSearch>"),
            (mt_prefix + "IfTagSearch\tMT[C]", mt_prefix + "IfTagSearch${1}>${2:Contents}</" + mt_prefix + "IfTagSearch>"),
            (mt_prefix + "IfTypeKeyToken\tMT[C]", mt_prefix + "IfTypeKeyToken${1}>${2:Contents}</" + mt_prefix + "IfTypeKeyToken>"),
            (mt_prefix + "IfUserAgent\tDynamicMTML[C]", mt_prefix + "IfUserAgent${1}>${2}</" + mt_prefix + "IfUserAgent>"),
            (mt_prefix + "IfUserHasPermission\tDynamicMTML[C]", mt_prefix + "IfUserHasPermission${1}>${2}</" + mt_prefix + "IfUserHasPermission>"),
            (mt_prefix + "IfWebsite\tMT[C]", mt_prefix + "IfWebsite${1}>${2:Contents}</" + mt_prefix + "IfWebsite>"),
            (mt_prefix + "MultiBlogIfLocalBlog\tMT[C]", mt_prefix + "MultiBlogIfLocalBlog${1}>${2:Contents}</" + mt_prefix + "MultiBlogIfLocalBlog>"),
            (mt_prefix + "PageIfTagged\tMT[C]", mt_prefix + "PageIfTagged${1}>${2:Contents}</" + mt_prefix + "PageIfTagged>"),
            (mt_prefix + "WebsiteIfCCLicense\tMT[C]", mt_prefix + "WebsiteIfCCLicense${1}>${2:Contents}</" + mt_prefix + "WebsiteIfCCLicense>"),
            (mt_prefix + "WebsiteIfCommentsOpen\tMT[C]", mt_prefix + "WebsiteIfCommentsOpen${1}>${2:Contents}</" + mt_prefix + "WebsiteIfCommentsOpen>"),
            # Function Tag
            ("mt\tMT[F]", tag_open + mt_prefix + "${1:TagName}" + tag_close),
            (mt_prefix + "AdminCGIPath\tMT[F]", tag_open + mt_prefix + "AdminCGIPath${1}" + tag_close),
            (mt_prefix + "AdminScript\tMT[F]", tag_open + mt_prefix + "AdminScript${1}" + tag_close),
            (mt_prefix + "ArchiveCategory\tMT[F]", tag_open + mt_prefix + "ArchiveCategory${1}" + tag_close),
            (mt_prefix + "ArchiveCount\tMT[F]", tag_open + mt_prefix + "ArchiveCount${1}" + tag_close),
            (mt_prefix + "ArchiveDate\tMT[F]", tag_open + mt_prefix + "ArchiveDate${1}" + tag_close),
            (mt_prefix + "ArchiveDateEnd\tMT[F]", tag_open + mt_prefix + "ArchiveDateEnd${1}" + tag_close),
            (mt_prefix + "ArchiveFile\tMT[F]", tag_open + mt_prefix + "ArchiveFile${1}" + tag_close),
            (mt_prefix + "ArchiveLabel\tMT[F]", tag_open + mt_prefix + "ArchiveLabel${1}" + tag_close),
            (mt_prefix + "ArchiveLink\tMT[F]", tag_open + mt_prefix + "ArchiveLink${1}" + tag_close),
            (mt_prefix + "ArchiveTitle\tMT[F]", tag_open + mt_prefix + "ArchiveTitle${1}" + tag_close),
            (mt_prefix + "ArchiveType\tMT[F]", tag_open + mt_prefix + "ArchiveType${1}" + tag_close),
            (mt_prefix + "ArchiveTypeLabel\tMT[F]", tag_open + mt_prefix + "ArchiveTypeLabel${1}" + tag_close),
            (mt_prefix + "AssetAddedBy\tMT[F]", tag_open + mt_prefix + "AssetAddedBy${1}" + tag_close),
            (mt_prefix + "AssetCount\tMT[F]", tag_open + mt_prefix + "AssetCount${1}" + tag_close),
            (mt_prefix + "AssetDateAdded\tMT[F]", tag_open + mt_prefix + "AssetDateAdded${1}" + tag_close),
            (mt_prefix + "AssetDescription\tMT[F]", tag_open + mt_prefix + "AssetDescription${1}" + tag_close),
            (mt_prefix + "AssetFileExt\tMT[F]", tag_open + mt_prefix + "AssetFileExt${1}" + tag_close),
            (mt_prefix + "AssetFileName\tMT[F]", tag_open + mt_prefix + "AssetFileName${1}" + tag_close),
            (mt_prefix + "AssetFilePath\tMT[F]", tag_open + mt_prefix + "AssetFilePath${1}" + tag_close),
            (mt_prefix + "AssetID\tMT[F]", tag_open + mt_prefix + "AssetID${1}" + tag_close),
            (mt_prefix + "AssetLabel\tMT[F]", tag_open + mt_prefix + "AssetLabel${1}" + tag_close),
            (mt_prefix + "AssetLink\tMT[F]", tag_open + mt_prefix + "AssetLink${1}" + tag_close),
            (mt_prefix + "AssetMimeType\tMT[F]", tag_open + mt_prefix + "AssetMimeType${1}" + tag_close),
            (mt_prefix + "AssetProperty\tMT[F]", tag_open + mt_prefix + "AssetProperty${1}" + tag_close),
            (mt_prefix + "AssetRank\tMT[F]", tag_open + mt_prefix + "AssetRank${1}" + tag_close),
            (mt_prefix + "AssetScore\tMT[F]", tag_open + mt_prefix + "AssetScore${1}" + tag_close),
            (mt_prefix + "AssetScoreAvg\tMT[F]", tag_open + mt_prefix + "AssetScoreAvg${1}" + tag_close),
            (mt_prefix + "AssetScoreCount\tMT[F]", tag_open + mt_prefix + "AssetScoreCount${1}" + tag_close),
            (mt_prefix + "AssetScoreHigh\tMT[F]", tag_open + mt_prefix + "AssetScoreHigh${1}" + tag_close),
            (mt_prefix + "AssetScoreLow\tMT[F]", tag_open + mt_prefix + "AssetScoreLow${1}" + tag_close),
            (mt_prefix + "AssetThumbnailLink\tMT[F]", tag_open + mt_prefix + "AssetThumbnailLink${1}" + tag_close),
            (mt_prefix + "AssetThumbnailURL\tMT[F]", tag_open + mt_prefix + "AssetThumbnailURL${1}" + tag_close),
            (mt_prefix + "AssetType\tMT[F]", tag_open + mt_prefix + "AssetType${1}" + tag_close),
            (mt_prefix + "AssetURL\tMT[F]", tag_open + mt_prefix + "AssetURL${1}" + tag_close),
            (mt_prefix + "AtomScript\tMT[F]", tag_open + mt_prefix + "AtomScript${1}" + tag_close),
            (mt_prefix + "AudioCustomFieldDescription\tMT[F]", tag_open + mt_prefix + "AudioCustomFieldDescription${1}" + tag_close),
            (mt_prefix + "AudioCustomFieldName\tMT[F]", tag_open + mt_prefix + "AudioCustomFieldName${1}" + tag_close),
            (mt_prefix + "AudioCustomFieldValue\tMT[F]", tag_open + mt_prefix + "AudioCustomFieldValue${1}" + tag_close),
            (mt_prefix + "AuthorAuthIconURL\tMT[F]", tag_open + mt_prefix + "AuthorAuthIconURL${1}" + tag_close),
            (mt_prefix + "AuthorAuthType\tMT[F]", tag_open + mt_prefix + "AuthorAuthType${1}" + tag_close),
            (mt_prefix + "AuthorBasename\tMT[F]", tag_open + mt_prefix + "AuthorBasename${1}" + tag_close),
            (mt_prefix + "AuthorCommentCount\tMT[F]", tag_open + mt_prefix + "AuthorCommentCount${1}" + tag_close),
            (mt_prefix + "AuthorCustomFieldDescription\tMT[F]", tag_open + mt_prefix + "AuthorCustomFieldDescription${1}" + tag_close),
            (mt_prefix + "AuthorCustomFieldName\tMT[F]", tag_open + mt_prefix + "AuthorCustomFieldName${1}" + tag_close),
            (mt_prefix + "AuthorCustomFieldValue\tMT[F]", tag_open + mt_prefix + "AuthorCustomFieldValue${1}" + tag_close),
            (mt_prefix + "AuthorDisplayName\tMT[F]", tag_open + mt_prefix + "AuthorDisplayName${1}" + tag_close),
            (mt_prefix + "AuthorEmail\tMT[F]", tag_open + mt_prefix + "AuthorEmail${1}" + tag_close),
            (mt_prefix + "AuthorEntriesCount\tMT[F]", tag_open + mt_prefix + "AuthorEntriesCount${1}" + tag_close),
            (mt_prefix + "AuthorEntryCount\tMT[F]", tag_open + mt_prefix + "AuthorEntryCount${1}" + tag_close),
            (mt_prefix + "AuthorFollowersCount\tMT[F]", tag_open + mt_prefix + "AuthorFollowersCount${1}" + tag_close),
            (mt_prefix + "AuthorFollowingCount\tMT[F]", tag_open + mt_prefix + "AuthorFollowingCount${1}" + tag_close),
            (mt_prefix + "AuthorFollowLink\tMT[F]", tag_open + mt_prefix + "AuthorFollowLink${1}" + tag_close),
            (mt_prefix + "AuthorID\tMT[F]", tag_open + mt_prefix + "AuthorID${1}" + tag_close),
            (mt_prefix + "AuthorLanguage\tDynamicMTML[F]", tag_open + mt_prefix + "AuthorLanguage${1}" + tag_close),
            (mt_prefix + "AuthorName\tMT[F]", tag_open + mt_prefix + "AuthorName${1}" + tag_close),
            (mt_prefix + "AuthorRank\tMT[F]", tag_open + mt_prefix + "AuthorRank${1}" + tag_close),
            (mt_prefix + "AuthorScore\tMT[F]", tag_open + mt_prefix + "AuthorScore${1}" + tag_close),
            (mt_prefix + "AuthorScoreAvg\tMT[F]", tag_open + mt_prefix + "AuthorScoreAvg${1}" + tag_close),
            (mt_prefix + "AuthorScoreCount\tMT[F]", tag_open + mt_prefix + "AuthorScoreCount${1}" + tag_close),
            (mt_prefix + "AuthorScoreHigh\tMT[F]", tag_open + mt_prefix + "AuthorScoreHigh${1}" + tag_close),
            (mt_prefix + "AuthorScoreLow\tMT[F]", tag_open + mt_prefix + "AuthorScoreLow${1}" + tag_close),
            (mt_prefix + "AuthorUnFollowLink\tMT[F]", tag_open + mt_prefix + "AuthorUnFollowLink${1}" + tag_close),
            (mt_prefix + "AuthorURL\tMT[F]", tag_open + mt_prefix + "AuthorURL${1}" + tag_close),
            (mt_prefix + "AuthorUserpic\tMT[F]", tag_open + mt_prefix + "AuthorUserpic${1}" + tag_close),
            (mt_prefix + "AuthorUserpicURL\tMT[F]", tag_open + mt_prefix + "AuthorUserpicURL${1}" + tag_close),
            (mt_prefix + "BlogArchiveURL\tMT[F]", tag_open + mt_prefix + "BlogArchiveURL${1}" + tag_close),
            (mt_prefix + "BlogCategoryCount\tMT[F]", tag_open + mt_prefix + "BlogCategoryCount${1}" + tag_close),
            (mt_prefix + "BlogCCLicenseImage\tMT[F]", tag_open + mt_prefix + "BlogCCLicenseImage${1}" + tag_close),
            (mt_prefix + "BlogCCLicenseURL\tMT[F]", tag_open + mt_prefix + "BlogCCLicenseURL${1}" + tag_close),
            (mt_prefix + "BlogCommentCount\tMT[F]", tag_open + mt_prefix + "BlogCommentCount${1}" + tag_close),
            (mt_prefix + "BlogCustomFieldDescription\tMT[F]", tag_open + mt_prefix + "BlogCustomFieldDescription${1}" + tag_close),
            (mt_prefix + "BlogCustomFieldName\tMT[F]", tag_open + mt_prefix + "BlogCustomFieldName${1}" + tag_close),
            (mt_prefix + "BlogCustomFieldValue\tMT[F]", tag_open + mt_prefix + "BlogCustomFieldValue${1}" + tag_close),
            (mt_prefix + "BlogDescription\tMT[F]", tag_open + mt_prefix + "BlogDescription${1}" + tag_close),
            (mt_prefix + "BlogEntryCount\tMT[F]", tag_open + mt_prefix + "BlogEntryCount${1}" + tag_close),
            (mt_prefix + "BlogFileExtension\tMT[F]", tag_open + mt_prefix + "BlogFileExtension${1}" + tag_close),
            (mt_prefix + "BlogHost\tMT[F]", tag_open + mt_prefix + "BlogHost${1}" + tag_close),
            (mt_prefix + "BlogID\tMT[F]", tag_open + mt_prefix + "BlogID${1}" + tag_close),
            (mt_prefix + "BlogLanguage\tMT[F]", tag_open + mt_prefix + "BlogLanguage${1}" + tag_close),
            (mt_prefix + "BlogName\tMT[F]", tag_open + mt_prefix + "BlogName${1}" + tag_close),
            (mt_prefix + "BlogPageCount\tMT[F]", tag_open + mt_prefix + "BlogPageCount${1}" + tag_close),
            (mt_prefix + "BlogPingCount\tMT[F]", tag_open + mt_prefix + "BlogPingCount${1}" + tag_close),
            (mt_prefix + "BlogRelativeURL\tMT[F]", tag_open + mt_prefix + "BlogRelativeURL${1}" + tag_close),
            (mt_prefix + "BlogSitePath\tMT[F]", tag_open + mt_prefix + "BlogSitePath${1}" + tag_close),
            (mt_prefix + "BlogTemplateSetID\tMT[F]", tag_open + mt_prefix + "BlogTemplateSetID${1}" + tag_close),
            (mt_prefix + "BlogThemeID\tMT[F]", tag_open + mt_prefix + "BlogThemeID${1}" + tag_close),
            (mt_prefix + "BlogTimezone\tMT[F]", tag_open + mt_prefix + "BlogTimezone${1}" + tag_close),
            (mt_prefix + "BlogURL\tMT[F]", tag_open + mt_prefix + "BlogURL${1}" + tag_close),
            (mt_prefix + "BuildTemplateID\tMT[F]", tag_open + mt_prefix + "BuildTemplateID${1}" + tag_close),
            (mt_prefix + "CalendarCellNumber\tMT[F]", tag_open + mt_prefix + "CalendarCellNumber${1}" + tag_close),
            (mt_prefix + "CalendarDate\tMT[F]", tag_open + mt_prefix + "CalendarDate${1}" + tag_close),
            (mt_prefix + "CalendarDay\tMT[F]", tag_open + mt_prefix + "CalendarDay${1}" + tag_close),
            (mt_prefix + "CaptchaFields\tMT[F]", tag_open + mt_prefix + "CaptchaFields${1}" + tag_close),
            (mt_prefix + "CategoryArchiveLink\tMT[F]", tag_open + mt_prefix + "CategoryArchiveLink${1}" + tag_close),
            (mt_prefix + "CategoryBasename\tMT[F]", tag_open + mt_prefix + "CategoryBasename${1}" + tag_close),
            (mt_prefix + "CategoryCommentCount\tMT[F]", tag_open + mt_prefix + "CategoryCommentCount${1}" + tag_close),
            (mt_prefix + "CategoryCount\tMT[F]", tag_open + mt_prefix + "CategoryCount${1}" + tag_close),
            (mt_prefix + "CategoryCustomFieldDescription\tMT[F]", tag_open + mt_prefix + "CategoryCustomFieldDescription${1}" + tag_close),
            (mt_prefix + "CategoryCustomFieldName\tMT[F]", tag_open + mt_prefix + "CategoryCustomFieldName${1}" + tag_close),
            (mt_prefix + "CategoryCustomFieldValue\tMT[F]", tag_open + mt_prefix + "CategoryCustomFieldValue${1}" + tag_close),
            (mt_prefix + "CategoryDescription\tMT[F]", tag_open + mt_prefix + "CategoryDescription${1}" + tag_close),
            (mt_prefix + "CategoryID\tMT[F]", tag_open + mt_prefix + "CategoryID${1}" + tag_close),
            (mt_prefix + "CategoryLabel\tMT[F]", tag_open + mt_prefix + "CategoryLabel${1}" + tag_close),
            (mt_prefix + "CategoryTrackbackCount\tMT[F]", tag_open + mt_prefix + "CategoryTrackbackCount${1}" + tag_close),
            (mt_prefix + "CategoryTrackbackLink\tMT[F]", tag_open + mt_prefix + "CategoryTrackbackLink${1}" + tag_close),
            (mt_prefix + "CCLicenseRDF\tMT[F]", tag_open + mt_prefix + "CCLicenseRDF${1}" + tag_close),
            (mt_prefix + "CGIHost\tMT[F]", tag_open + mt_prefix + "CGIHost${1}" + tag_close),
            (mt_prefix + "CGIPath\tMT[F]", tag_open + mt_prefix + "CGIPath${1}" + tag_close),
            (mt_prefix + "CGIRelativeURL\tMT[F]", tag_open + mt_prefix + "CGIRelativeURL${1}" + tag_close),
            (mt_prefix + "CGIServerPath\tMT[F]", tag_open + mt_prefix + "CGIServerPath${1}" + tag_close),
            (mt_prefix + "CommentAuthor\tMT[F]", tag_open + mt_prefix + "CommentAuthor${1}" + tag_close),
            (mt_prefix + "CommentAuthorIdentity\tMT[F]", tag_open + mt_prefix + "CommentAuthorIdentity${1}" + tag_close),
            (mt_prefix + "CommentAuthorLink\tMT[F]", tag_open + mt_prefix + "CommentAuthorLink${1}" + tag_close),
            (mt_prefix + "CommentBlogID\tMT[F]", tag_open + mt_prefix + "CommentBlogID${1}" + tag_close),
            (mt_prefix + "CommentBody\tMT[F]", tag_open + mt_prefix + "CommentBody${1}" + tag_close),
            (mt_prefix + "CommentCustomFieldDescription\tMT[F]", tag_open + mt_prefix + "CommentCustomFieldDescription${1}" + tag_close),
            (mt_prefix + "CommentCustomFieldName\tMT[F]", tag_open + mt_prefix + "CommentCustomFieldName${1}" + tag_close),
            (mt_prefix + "CommentCustomFieldValue\tMT[F]", tag_open + mt_prefix + "CommentCustomFieldValue${1}" + tag_close),
            (mt_prefix + "CommentDate\tMT[F]", tag_open + mt_prefix + "CommentDate${1}" + tag_close),
            (mt_prefix + "CommentEmail\tMT[F]", tag_open + mt_prefix + "CommentEmail${1}" + tag_close),
            (mt_prefix + "CommentEntryID\tMT[F]", tag_open + mt_prefix + "CommentEntryID${1}" + tag_close),
            (mt_prefix + "CommenterAuthIconURL\tMT[F]", tag_open + mt_prefix + "CommenterAuthIconURL${1}" + tag_close),
            (mt_prefix + "CommenterAuthType\tMT[F]", tag_open + mt_prefix + "CommenterAuthType${1}" + tag_close),
            (mt_prefix + "CommenterEmail\tMT[F]", tag_open + mt_prefix + "CommenterEmail${1}" + tag_close),
            (mt_prefix + "CommenterID\tMT[F]", tag_open + mt_prefix + "CommenterID${1}" + tag_close),
            (mt_prefix + "CommenterName\tMT[F]", tag_open + mt_prefix + "CommenterName${1}" + tag_close),
            (mt_prefix + "CommenterNameThunk\tMT[F]", tag_open + mt_prefix + "CommenterNameThunk${1}" + tag_close),
            (mt_prefix + "CommenterURL\tMT[F]", tag_open + mt_prefix + "CommenterURL${1}" + tag_close),
            (mt_prefix + "CommenterUsername\tMT[F]", tag_open + mt_prefix + "CommenterUsername${1}" + tag_close),
            (mt_prefix + "CommenterUserpic\tMT[F]", tag_open + mt_prefix + "CommenterUserpic${1}" + tag_close),
            (mt_prefix + "CommenterUserpicURL\tMT[F]", tag_open + mt_prefix + "CommenterUserpicURL${1}" + tag_close),
            (mt_prefix + "CommentID\tMT[F]", tag_open + mt_prefix + "CommentID${1}" + tag_close),
            (mt_prefix + "CommentIP\tMT[F]", tag_open + mt_prefix + "CommentIP${1}" + tag_close),
            (mt_prefix + "CommentLink\tMT[F]", tag_open + mt_prefix + "CommentLink${1}" + tag_close),
            (mt_prefix + "CommentName\tMT[F]", tag_open + mt_prefix + "CommentName${1}" + tag_close),
            (mt_prefix + "CommentOrderNumber\tMT[F]", tag_open + mt_prefix + "CommentOrderNumber${1}" + tag_close),
            (mt_prefix + "CommentParentID\tMT[F]", tag_open + mt_prefix + "CommentParentID${1}" + tag_close),
            (mt_prefix + "CommentPreviewAuthor\tMT[F]", tag_open + mt_prefix + "CommentPreviewAuthor${1}" + tag_close),
            (mt_prefix + "CommentPreviewAuthorLink\tMT[F]", tag_open + mt_prefix + "CommentPreviewAuthorLink${1}" + tag_close),
            (mt_prefix + "CommentPreviewBody\tMT[F]", tag_open + mt_prefix + "CommentPreviewBody${1}" + tag_close),
            (mt_prefix + "CommentPreviewDate\tMT[F]", tag_open + mt_prefix + "CommentPreviewDate${1}" + tag_close),
            (mt_prefix + "CommentPreviewEmail\tMT[F]", tag_open + mt_prefix + "CommentPreviewEmail${1}" + tag_close),
            (mt_prefix + "CommentPreviewIP\tMT[F]", tag_open + mt_prefix + "CommentPreviewIP${1}" + tag_close),
            (mt_prefix + "CommentPreviewIsStatic\tMT[F]", tag_open + mt_prefix + "CommentPreviewIsStatic${1}" + tag_close),
            (mt_prefix + "CommentPreviewURL\tMT[F]", tag_open + mt_prefix + "CommentPreviewURL${1}" + tag_close),
            (mt_prefix + "CommentRank\tMT[F]", tag_open + mt_prefix + "CommentRank${1}" + tag_close),
            (mt_prefix + "CommentRepliesRecurse\tMT[F]", tag_open + mt_prefix + "CommentRepliesRecurse${1}" + tag_close),
            (mt_prefix + "CommentScore\tMT[F]", tag_open + mt_prefix + "CommentScore${1}" + tag_close),
            (mt_prefix + "CommentScoreAvg\tMT[F]", tag_open + mt_prefix + "CommentScoreAvg${1}" + tag_close),
            (mt_prefix + "CommentScoreCount\tMT[F]", tag_open + mt_prefix + "CommentScoreCount${1}" + tag_close),
            (mt_prefix + "CommentScoreHigh\tMT[F]", tag_open + mt_prefix + "CommentScoreHigh${1}" + tag_close),
            (mt_prefix + "CommentScoreLow\tMT[F]", tag_open + mt_prefix + "CommentScoreLow${1}" + tag_close),
            (mt_prefix + "CommentScript\tMT[F]", tag_open + mt_prefix + "CommentScript${1}" + tag_close),
            (mt_prefix + "CommentURL\tMT[F]", tag_open + mt_prefix + "CommentURL${1}" + tag_close),
            (mt_prefix + "CommunityScript\tMT[F]", tag_open + mt_prefix + "CommunityScript${1}" + tag_close),
            (mt_prefix + "ConfigFile\tMT[F]", tag_open + mt_prefix + "ConfigFile${1}" + tag_close),
            (mt_prefix + "CurrentArchiveFile\tDynamicMTML[F]", tag_open + mt_prefix + "CurrentArchiveFile${1}" + tag_close),
            (mt_prefix + "CurrentArchiveURL\tDynamicMTML[F]", tag_open + mt_prefix + "CurrentArchiveURL${1}" + tag_close),
            (mt_prefix + "CurrentPage\tMT[F]", tag_open + mt_prefix + "CurrentPage${1}" + tag_close),
            (mt_prefix + "CustomFieldBasename\tMT[F]", tag_open + mt_prefix + "CustomFieldBasename${1}" + tag_close),
            (mt_prefix + "CustomFieldDescription\tMT[F]", tag_open + mt_prefix + "CustomFieldDescription${1}" + tag_close),
            (mt_prefix + "CustomFieldHTML\tMT[F]", tag_open + mt_prefix + "CustomFieldHTML${1}" + tag_close),
            (mt_prefix + "CustomFieldName\tMT[F]", tag_open + mt_prefix + "CustomFieldName${1}" + tag_close),
            (mt_prefix + "CustomFieldValue\tMT[F]", tag_open + mt_prefix + "CustomFieldValue${1}" + tag_close),
            (mt_prefix + "Date\tMT[F]", tag_open + mt_prefix + "Date${1}" + tag_close),
            (mt_prefix + "DefaultLanguage\tMT[F]", tag_open + mt_prefix + "DefaultLanguage${1}" + tag_close),
            (mt_prefix + "EntriesCount\tMT[F]", tag_open + mt_prefix + "EntriesCount${1}" + tag_close),
            (mt_prefix + "EntryAtomID\tMT[F]", tag_open + mt_prefix + "EntryAtomID${1}" + tag_close),
            (mt_prefix + "EntryAudio\tMT[F]", tag_open + mt_prefix + "EntryAudio${1}" + tag_close),
            (mt_prefix + "EntryAuthor\tMT[F]", tag_open + mt_prefix + "EntryAuthor${1}" + tag_close),
            (mt_prefix + "EntryAuthorDisplayName\tMT[F]", tag_open + mt_prefix + "EntryAuthorDisplayName${1}" + tag_close),
            (mt_prefix + "EntryAuthorEmail\tMT[F]", tag_open + mt_prefix + "EntryAuthorEmail${1}" + tag_close),
            (mt_prefix + "EntryAuthorID\tMT[F]", tag_open + mt_prefix + "EntryAuthorID${1}" + tag_close),
            (mt_prefix + "EntryAuthorLink\tMT[F]", tag_open + mt_prefix + "EntryAuthorLink${1}" + tag_close),
            (mt_prefix + "EntryAuthorNickname\tMT[F]", tag_open + mt_prefix + "EntryAuthorNickname${1}" + tag_close),
            (mt_prefix + "EntryAuthorURL\tMT[F]", tag_open + mt_prefix + "EntryAuthorURL${1}" + tag_close),
            (mt_prefix + "EntryAuthorUsername\tMT[F]", tag_open + mt_prefix + "EntryAuthorUsername${1}" + tag_close),
            (mt_prefix + "EntryAuthorUserpic\tMT[F]", tag_open + mt_prefix + "EntryAuthorUserpic${1}" + tag_close),
            (mt_prefix + "EntryAuthorUserpicURL\tMT[F]", tag_open + mt_prefix + "EntryAuthorUserpicURL${1}" + tag_close),
            (mt_prefix + "EntryBasename\tMT[F]", tag_open + mt_prefix + "EntryBasename${1}" + tag_close),
            (mt_prefix + "EntryBlogDescription\tMT[F]", tag_open + mt_prefix + "EntryBlogDescription${1}" + tag_close),
            (mt_prefix + "EntryBlogID\tMT[F]", tag_open + mt_prefix + "EntryBlogID${1}" + tag_close),
            (mt_prefix + "EntryBlogName\tMT[F]", tag_open + mt_prefix + "EntryBlogName${1}" + tag_close),
            (mt_prefix + "EntryBlogURL\tMT[F]", tag_open + mt_prefix + "EntryBlogURL${1}" + tag_close),
            (mt_prefix + "EntryBody\tMT[F]", tag_open + mt_prefix + "EntryBody${1}" + tag_close),
            (mt_prefix + "EntryCategory\tMT[F]", tag_open + mt_prefix + "EntryCategory${1}" + tag_close),
            (mt_prefix + "EntryClass\tMT[F]", tag_open + mt_prefix + "EntryClass${1}" + tag_close),
            (mt_prefix + "EntryClassLabel\tMT[F]", tag_open + mt_prefix + "EntryClassLabel${1}" + tag_close),
            (mt_prefix + "EntryCommentCount\tMT[F]", tag_open + mt_prefix + "EntryCommentCount${1}" + tag_close),
            (mt_prefix + "EntryCreatedDate\tMT[F]", tag_open + mt_prefix + "EntryCreatedDate${1}" + tag_close),
            (mt_prefix + "EntryCustomFieldDescription\tMT[F]", tag_open + mt_prefix + "EntryCustomFieldDescription${1}" + tag_close),
            (mt_prefix + "EntryCustomFieldName\tMT[F]", tag_open + mt_prefix + "EntryCustomFieldName${1}" + tag_close),
            (mt_prefix + "EntryCustomFieldValue\tMT[F]", tag_open + mt_prefix + "EntryCustomFieldValue${1}" + tag_close),
            (mt_prefix + "EntryDate\tMT[F]", tag_open + mt_prefix + "EntryDate${1}" + tag_close),
            (mt_prefix + "EntryEditLink\tMT[F]", tag_open + mt_prefix + "EntryEditLink${1}" + tag_close),
            (mt_prefix + "EntryEmbedCode\tMT[F]", tag_open + mt_prefix + "EntryEmbedCode${1}" + tag_close),
            (mt_prefix + "EntryExcerpt\tMT[F]", tag_open + mt_prefix + "EntryExcerpt${1}" + tag_close),
            (mt_prefix + "EntryFlag\tMT[F]", tag_open + mt_prefix + "EntryFlag${1}" + tag_close),
            (mt_prefix + "EntryID\tMT[F]", tag_open + mt_prefix + "EntryID${1}" + tag_close),
            (mt_prefix + "EntryKeywords\tMT[F]", tag_open + mt_prefix + "EntryKeywords${1}" + tag_close),
            (mt_prefix + "EntryLink\tMT[F]", tag_open + mt_prefix + "EntryLink${1}" + tag_close),
            (mt_prefix + "EntryLinkURL\tMT[F]", tag_open + mt_prefix + "EntryLinkURL${1}" + tag_close),
            (mt_prefix + "EntryModifiedDate\tMT[F]", tag_open + mt_prefix + "EntryModifiedDate${1}" + tag_close),
            (mt_prefix + "EntryMore\tMT[F]", tag_open + mt_prefix + "EntryMore${1}" + tag_close),
            (mt_prefix + "EntryPermalink\tMT[F]", tag_open + mt_prefix + "EntryPermalink${1}" + tag_close),
            (mt_prefix + "EntryPhoto\tMT[F]", tag_open + mt_prefix + "EntryPhoto${1}" + tag_close),
            (mt_prefix + "EntryPostType\tMT[F]", tag_open + mt_prefix + "EntryPostType${1}" + tag_close),
            (mt_prefix + "EntryRank\tMT[F]", tag_open + mt_prefix + "EntryRank${1}" + tag_close),
            (mt_prefix + "EntryRawPostType\tMT[F]", tag_open + mt_prefix + "EntryRawPostType${1}" + tag_close),
            (mt_prefix + "EntryRecommendedTotal\tMT[F]", tag_open + mt_prefix + "EntryRecommendedTotal${1}" + tag_close),
            (mt_prefix + "EntryRecommendVoteLink\tMT[F]", tag_open + mt_prefix + "EntryRecommendVoteLink${1}" + tag_close),
            (mt_prefix + "EntryScore\tMT[F]", tag_open + mt_prefix + "EntryScore${1}" + tag_close),
            (mt_prefix + "EntryScoreAvg\tMT[F]", tag_open + mt_prefix + "EntryScoreAvg${1}" + tag_close),
            (mt_prefix + "EntryScoreCount\tMT[F]", tag_open + mt_prefix + "EntryScoreCount${1}" + tag_close),
            (mt_prefix + "EntryScoreHigh\tMT[F]", tag_open + mt_prefix + "EntryScoreHigh${1}" + tag_close),
            (mt_prefix + "EntryScoreLow\tMT[F]", tag_open + mt_prefix + "EntryScoreLow${1}" + tag_close),
            (mt_prefix + "EntryStatus\tMT[F]", tag_open + mt_prefix + "EntryStatus${1}" + tag_close),
            (mt_prefix + "EntryStatusInt\tDynamicMTML[F]", tag_open + mt_prefix + "EntryStatusInt${1}" + tag_close),
            (mt_prefix + "EntryTitle\tMT[F]", tag_open + mt_prefix + "EntryTitle${1: escape=\"html\"}" + tag_close),
            (mt_prefix + "EntryTrackbackCount\tMT[F]", tag_open + mt_prefix + "EntryTrackbackCount${1}" + tag_close),
            (mt_prefix + "EntryTrackbackData\tMT[F]", tag_open + mt_prefix + "EntryTrackbackData${1}" + tag_close),
            (mt_prefix + "EntryTrackbackID\tMT[F]", tag_open + mt_prefix + "EntryTrackbackID${1}" + tag_close),
            (mt_prefix + "EntryTrackbackLink\tMT[F]", tag_open + mt_prefix + "EntryTrackbackLink${1}" + tag_close),
            (mt_prefix + "ErrorMessage\tMT[F]", tag_open + mt_prefix + "ErrorMessage${1}" + tag_close),
            (mt_prefix + "FeedbackScore\tMT[F]", tag_open + mt_prefix + "FeedbackScore${1}" + tag_close),
            (mt_prefix + "FeedEntryLink\tMT[F]", tag_open + mt_prefix + "FeedEntryLink${1}" + tag_close),
            (mt_prefix + "FeedEntryTitle\tMT[F]", tag_open + mt_prefix + "FeedEntryTitle${1}" + tag_close),
            (mt_prefix + "FeedInclude\tMT[F]", tag_open + mt_prefix + "FeedInclude${1}" + tag_close),
            (mt_prefix + "FeedLink\tMT[F]", tag_open + mt_prefix + "FeedLink${1}" + tag_close),
            (mt_prefix + "FeedTitle\tMT[F]", tag_open + mt_prefix + "FeedTitle${1}" + tag_close),
            (mt_prefix + "FileCustomFieldDescription\tMT[F]", tag_open + mt_prefix + "FileCustomFieldDescription${1}" + tag_close),
            (mt_prefix + "FileCustomFieldName\tMT[F]", tag_open + mt_prefix + "FileCustomFieldName${1}" + tag_close),
            (mt_prefix + "FileCustomFieldValue\tMT[F]", tag_open + mt_prefix + "FileCustomFieldValue${1}" + tag_close),
            (mt_prefix + "FileTemplate\tMT[F]", tag_open + mt_prefix + "FileTemplate${1}" + tag_close),
            (mt_prefix + "FolderBasename\tMT[F]", tag_open + mt_prefix + "FolderBasename${1}" + tag_close),
            (mt_prefix + "FolderCount\tMT[F]", tag_open + mt_prefix + "FolderCount${1}" + tag_close),
            (mt_prefix + "FolderCustomFieldDescription\tMT[F]", tag_open + mt_prefix + "FolderCustomFieldDescription${1}" + tag_close),
            (mt_prefix + "FolderCustomFieldName\tMT[F]", tag_open + mt_prefix + "FolderCustomFieldName${1}" + tag_close),
            (mt_prefix + "FolderCustomFieldValue\tMT[F]", tag_open + mt_prefix + "FolderCustomFieldValue${1}" + tag_close),
            (mt_prefix + "FolderDescription\tMT[F]", tag_open + mt_prefix + "FolderDescription${1}" + tag_close),
            (mt_prefix + "FolderID\tMT[F]", tag_open + mt_prefix + "FolderID${1}" + tag_close),
            (mt_prefix + "FolderLabel\tMT[F]", tag_open + mt_prefix + "FolderLabel${1}" + tag_close),
            (mt_prefix + "FolderPath\tMT[F]", tag_open + mt_prefix + "FolderPath${1}" + tag_close),
            (mt_prefix + "GetVar\tMT[F]", tag_open + mt_prefix + "GetVar${1}" + tag_close),
            (mt_prefix + "HTTPContentType\tMT[F]", tag_open + mt_prefix + "HTTPContentType${1}" + tag_close),
            (mt_prefix + "ImageCustomFieldDescription\tMT[F]", tag_open + mt_prefix + "ImageCustomFieldDescription${1}" + tag_close),
            (mt_prefix + "ImageCustomFieldName\tMT[F]", tag_open + mt_prefix + "ImageCustomFieldName${1}" + tag_close),
            (mt_prefix + "ImageCustomFieldValue\tMT[F]", tag_open + mt_prefix + "ImageCustomFieldValue${1}" + tag_close),
            (mt_prefix + "ImageHeight\tMT[F]", tag_open + mt_prefix + "ImageHeight${1}" + tag_close),
            (mt_prefix + "ImageURL\tMT[F]", tag_open + mt_prefix + "ImageURL${1}" + tag_close),
            (mt_prefix + "ImageWidth\tMT[F]", tag_open + mt_prefix + "ImageWidth${1}" + tag_close),
            (mt_prefix + "Include\tMT[F]", tag_open + mt_prefix + "Include module=\"${1:Module Name}\"" + tag_close),
            (mt_prefix + "Include module\tMT[F]", tag_open + mt_prefix + "Include module=\"${1:module}\"" + tag_close),
            (mt_prefix + "IndexBasename\tMT[F]", tag_open + mt_prefix + "IndexBasename${1}" + tag_close),
            (mt_prefix + "IndexLink\tMT[F]", tag_open + mt_prefix + "IndexLink${1}" + tag_close),
            (mt_prefix + "IndexName\tMT[F]", tag_open + mt_prefix + "IndexName${1}" + tag_close),
            (mt_prefix + "Link\tMT[F]", tag_open + mt_prefix + "Link${1}" + tag_close),
            (mt_prefix + "MaxResults\tMT[F]", tag_open + mt_prefix + "MaxResults${1}" + tag_close),
            (mt_prefix + "NextLink\tMT[F]", tag_open + mt_prefix + "NextLink${1}" + tag_close),
            (mt_prefix + "NotifyScript\tMT[F]", tag_open + mt_prefix + "NotifyScript${1}" + tag_close),
            (mt_prefix + "OtherProfileVar\tMT[F]", tag_open + mt_prefix + "OtherProfileVar${1}" + tag_close),
            (mt_prefix + "PageAuthorDisplayName\tMT[F]", tag_open + mt_prefix + "PageAuthorDisplayName${1}" + tag_close),
            (mt_prefix + "PageAuthorEmail\tMT[F]", tag_open + mt_prefix + "PageAuthorEmail${1}" + tag_close),
            (mt_prefix + "PageAuthorLink\tMT[F]", tag_open + mt_prefix + "PageAuthorLink${1}" + tag_close),
            (mt_prefix + "PageAuthorURL\tMT[F]", tag_open + mt_prefix + "PageAuthorURL${1}" + tag_close),
            (mt_prefix + "PageBasename\tMT[F]", tag_open + mt_prefix + "PageBasename${1}" + tag_close),
            (mt_prefix + "PageBody\tMT[F]", tag_open + mt_prefix + "PageBody${1}" + tag_close),
            (mt_prefix + "PageCustomFieldDescription\tMT[F]", tag_open + mt_prefix + "PageCustomFieldDescription${1}" + tag_close),
            (mt_prefix + "PageCustomFieldName\tMT[F]", tag_open + mt_prefix + "PageCustomFieldName${1}" + tag_close),
            (mt_prefix + "PageCustomFieldValue\tMT[F]", tag_open + mt_prefix + "PageCustomFieldValue${1}" + tag_close),
            (mt_prefix + "PageDate\tMT[F]", tag_open + mt_prefix + "PageDate${1}" + tag_close),
            (mt_prefix + "PageExcerpt\tMT[F]", tag_open + mt_prefix + "PageExcerpt${1}" + tag_close),
            (mt_prefix + "PageID\tMT[F]", tag_open + mt_prefix + "PageID${1}" + tag_close),
            (mt_prefix + "PageKeywords\tMT[F]", tag_open + mt_prefix + "PageKeywords${1}" + tag_close),
            (mt_prefix + "PageModifiedDate\tMT[F]", tag_open + mt_prefix + "PageModifiedDate${1}" + tag_close),
            (mt_prefix + "PageMore\tMT[F]", tag_open + mt_prefix + "PageMore${1}" + tag_close),
            (mt_prefix + "PagePermalink\tMT[F]", tag_open + mt_prefix + "PagePermalink${1}" + tag_close),
            (mt_prefix + "PagerLink\tMT[F]", tag_open + mt_prefix + "PagerLink${1}" + tag_close),
            (mt_prefix + "PageTitle\tMT[F]", tag_open + mt_prefix + "PageTitle${1: escape=\"html\"}" + tag_close),
            (mt_prefix + "PingBlogName\tMT[F]", tag_open + mt_prefix + "PingBlogName${1}" + tag_close),
            (mt_prefix + "PingDate\tMT[F]", tag_open + mt_prefix + "PingDate${1}" + tag_close),
            (mt_prefix + "PingExcerpt\tMT[F]", tag_open + mt_prefix + "PingExcerpt${1}" + tag_close),
            (mt_prefix + "PingID\tMT[F]", tag_open + mt_prefix + "PingID${1}" + tag_close),
            (mt_prefix + "PingIP\tMT[F]", tag_open + mt_prefix + "PingIP${1}" + tag_close),
            (mt_prefix + "PingRank\tMT[F]", tag_open + mt_prefix + "PingRank${1}" + tag_close),
            (mt_prefix + "PingScore\tMT[F]", tag_open + mt_prefix + "PingScore${1}" + tag_close),
            (mt_prefix + "PingScoreAvg\tMT[F]", tag_open + mt_prefix + "PingScoreAvg${1}" + tag_close),
            (mt_prefix + "PingScoreCount\tMT[F]", tag_open + mt_prefix + "PingScoreCount${1}" + tag_close),
            (mt_prefix + "PingScoreHigh\tMT[F]", tag_open + mt_prefix + "PingScoreHigh${1}" + tag_close),
            (mt_prefix + "PingScoreLow\tMT[F]", tag_open + mt_prefix + "PingScoreLow${1}" + tag_close),
            (mt_prefix + "PingsSentURL\tMT[F]", tag_open + mt_prefix + "PingsSentURL${1}" + tag_close),
            (mt_prefix + "PingTitle\tMT[F]", tag_open + mt_prefix + "PingTitle${1}" + tag_close),
            (mt_prefix + "PingURL\tMT[F]", tag_open + mt_prefix + "PingURL${1}" + tag_close),
            (mt_prefix + "PreviousLink\tMT[F]", tag_open + mt_prefix + "PreviousLink${1}" + tag_close),
            (mt_prefix + "ProductName\tMT[F]", tag_open + mt_prefix + "ProductName${1}" + tag_close),
            (mt_prefix + "PublishCharset\tMT[F]", tag_open + mt_prefix + "PublishCharset${1}" + tag_close),
            (mt_prefix + "Query\tDynamicMTML[F]", tag_open + mt_prefix + "Query${1}" + tag_close),
            (mt_prefix + "Rand\tDynamicMTML[F]", tag_open + mt_prefix + "Rand${1}" + tag_close),
            (mt_prefix + "ReferralKeyword\tDynamicMTML[F]", tag_open + mt_prefix + "ReferralKeyword${1}" + tag_close),
            (mt_prefix + "RemoteSignInLink\tMT[F]", tag_open + mt_prefix + "RemoteSignInLink${1}" + tag_close),
            (mt_prefix + "RemoteSignOutLink\tMT[F]", tag_open + mt_prefix + "RemoteSignOutLink${1}" + tag_close),
            (mt_prefix + "SearchIncludeBlogs\tMT[F]", tag_open + mt_prefix + "SearchIncludeBlogs${1}" + tag_close),
            (mt_prefix + "SearchMaxResults\tMT[F]", tag_open + mt_prefix + "SearchMaxResults${1}" + tag_close),
            (mt_prefix + "SearchResultCount\tMT[F]", tag_open + mt_prefix + "SearchResultCount${1}" + tag_close),
            (mt_prefix + "SearchScript\tMT[F]", tag_open + mt_prefix + "SearchScript${1}" + tag_close),
            (mt_prefix + "SearchString\tMT[F]", tag_open + mt_prefix + "SearchString${1}" + tag_close),
            (mt_prefix + "SearchTemplateID\tMT[F]", tag_open + mt_prefix + "SearchTemplateID${1}" + tag_close),
            (mt_prefix + "SetVar\tMT[F]", tag_open + mt_prefix + "SetVar name=\"${1:VariableName}\" value=\"${2:Value}\"" + tag_close),
            (mt_prefix + "SignOnURL\tMT[F]", tag_open + mt_prefix + "SignOnURL${1}" + tag_close),
            (mt_prefix + "SmartyPantsVersion\tMT[F]", tag_open + mt_prefix + "SmartyPantsVersion${1}" + tag_close),
            (mt_prefix + "StaticFilePath\tMT[F]", tag_open + mt_prefix + "StaticFilePath${1}" + tag_close),
            (mt_prefix + "StaticWebPath\tMT[F]", tag_open + mt_prefix + "StaticWebPath${1}" + tag_close),
            (mt_prefix + "StreamAction\tMT[F]", tag_open + mt_prefix + "StreamAction${1}" + tag_close),
            (mt_prefix + "StreamActionDate\tMT[F]", tag_open + mt_prefix + "StreamActionDate${1}" + tag_close),
            (mt_prefix + "StreamActionID\tMT[F]", tag_open + mt_prefix + "StreamActionID${1}" + tag_close),
            (mt_prefix + "StreamActionModifiedDate\tMT[F]", tag_open + mt_prefix + "StreamActionModifiedDate${1}" + tag_close),
            (mt_prefix + "StreamActionThumbnailURL\tMT[F]", tag_open + mt_prefix + "StreamActionThumbnailURL${1}" + tag_close),
            (mt_prefix + "StreamActionTitle\tMT[F]", tag_open + mt_prefix + "StreamActionTitle${1}" + tag_close),
            (mt_prefix + "StreamActionVar\tMT[F]", tag_open + mt_prefix + "StreamActionVar${1}" + tag_close),
            (mt_prefix + "SubCategoryPath\tMT[F]", tag_open + mt_prefix + "SubCategoryPath${1}" + tag_close),
            (mt_prefix + "SubCatsRecurse\tMT[F]", tag_open + mt_prefix + "SubCatsRecurse${1}" + tag_close),
            (mt_prefix + "SubFolderRecurse\tMT[F]", tag_open + mt_prefix + "SubFolderRecurse${1}" + tag_close),
            (mt_prefix + "SupportDirectoryURL\tMT[F]", tag_open + mt_prefix + "SupportDirectoryURL${1}" + tag_close),
            (mt_prefix + "TagCount\tMT[F]", tag_open + mt_prefix + "TagCount${1}" + tag_close),
            (mt_prefix + "TagID\tMT[F]", tag_open + mt_prefix + "TagID${1}" + tag_close),
            (mt_prefix + "TagLabel\tMT[F]", tag_open + mt_prefix + "TagLabel${1}" + tag_close),
            (mt_prefix + "TagName\tMT[F]", tag_open + mt_prefix + "TagName${1}" + tag_close),
            (mt_prefix + "TagRank\tMT[F]", tag_open + mt_prefix + "TagRank${1}" + tag_close),
            (mt_prefix + "TagSearchLink\tMT[F]", tag_open + mt_prefix + "TagSearchLink${1}" + tag_close),
            (mt_prefix + "TemplateCreatedOn\tMT[F]", tag_open + mt_prefix + "TemplateCreatedOn${1}" + tag_close),
            (mt_prefix + "TemplateCustomFieldDescription\tMT[F]", tag_open + mt_prefix + "TemplateCustomFieldDescription${1}" + tag_close),
            (mt_prefix + "TemplateCustomFieldName\tMT[F]", tag_open + mt_prefix + "TemplateCustomFieldName${1}" + tag_close),
            (mt_prefix + "TemplateCustomFieldValue\tMT[F]", tag_open + mt_prefix + "TemplateCustomFieldValue${1}" + tag_close),
            (mt_prefix + "TemplateNote\tMT[F]", tag_open + mt_prefix + "TemplateNote value=\"${1:Comment}\"" + tag_close),
            (mt_prefix + "TextileHeadOffset\tMT[F]", tag_open + mt_prefix + "TextileHeadOffset${1}" + tag_close),
            (mt_prefix + "TextileOptions\tMT[F]", tag_open + mt_prefix + "TextileOptions${1}" + tag_close),
            (mt_prefix + "TotalPages\tMT[F]", tag_open + mt_prefix + "TotalPages${1}" + tag_close),
            (mt_prefix + "TrackbackScript\tMT[F]", tag_open + mt_prefix + "TrackbackScript${1}" + tag_close),
            (mt_prefix + "Trans\tDynamicMTML[F]", tag_open + mt_prefix + "Trans${1}" + tag_close),
            (mt_prefix + "TypeKeyToken\tMT[F]", tag_open + mt_prefix + "TypeKeyToken${1}" + tag_close),
            (mt_prefix + "UserAgent\tDynamicMTML[F]", tag_open + mt_prefix + "UserAgent${1}" + tag_close),
            (mt_prefix + "Var\tMT[F]", tag_open + mt_prefix + "Var name=\"${1:name}\"" + tag_close),
            (mt_prefix + "Var\tMT[F]", tag_open + mt_prefix + "Var${1}" + tag_close),
            (mt_prefix + "Version\tMT[F]", tag_open + mt_prefix + "Version${1}" + tag_close),
            (mt_prefix + "VideoCustomFieldDescription\tMT[F]", tag_open + mt_prefix + "VideoCustomFieldDescription${1}" + tag_close),
            (mt_prefix + "VideoCustomFieldName\tMT[F]", tag_open + mt_prefix + "VideoCustomFieldName${1}" + tag_close),
            (mt_prefix + "VideoCustomFieldValue\tMT[F]", tag_open + mt_prefix + "VideoCustomFieldValue${1}" + tag_close),
            (mt_prefix + "WebsiteCCLicenseImage\tMT[F]", tag_open + mt_prefix + "WebsiteCCLicenseImage${1}" + tag_close),
            (mt_prefix + "WebsiteCCLicenseURL\tMT[F]", tag_open + mt_prefix + "WebsiteCCLicenseURL${1}" + tag_close),
            (mt_prefix + "WebsiteCommentCount\tMT[F]", tag_open + mt_prefix + "WebsiteCommentCount${1}" + tag_close),
            (mt_prefix + "WebsiteCustomFieldDescription\tMT[F]", tag_open + mt_prefix + "WebsiteCustomFieldDescription${1}" + tag_close),
            (mt_prefix + "WebsiteCustomFieldName\tMT[F]", tag_open + mt_prefix + "WebsiteCustomFieldName${1}" + tag_close),
            (mt_prefix + "WebsiteCustomFieldValue\tMT[F]", tag_open + mt_prefix + "WebsiteCustomFieldValue${1}" + tag_close),
            (mt_prefix + "WebsiteDescription\tMT[F]", tag_open + mt_prefix + "WebsiteDescription${1}" + tag_close),
            (mt_prefix + "WebsiteFileExtension\tMT[F]", tag_open + mt_prefix + "WebsiteFileExtension${1}" + tag_close),
            (mt_prefix + "WebsiteHost\tMT[F]", tag_open + mt_prefix + "WebsiteHost${1}" + tag_close),
            (mt_prefix + "WebsiteID\tMT[F]", tag_open + mt_prefix + "WebsiteID${1}" + tag_close),
            (mt_prefix + "WebsiteLanguage\tMT[F]", tag_open + mt_prefix + "WebsiteLanguage${1}" + tag_close),
            (mt_prefix + "WebsiteName\tMT[F]", tag_open + mt_prefix + "WebsiteName${1}" + tag_close),
            (mt_prefix + "WebsitePageCount\tMT[F]", tag_open + mt_prefix + "WebsitePageCount${1}" + tag_close),
            (mt_prefix + "WebsitePath\tMT[F]", tag_open + mt_prefix + "WebsitePath${1}" + tag_close),
            (mt_prefix + "WebsitePingCount\tMT[F]", tag_open + mt_prefix + "WebsitePingCount${1}" + tag_close),
            (mt_prefix + "WebsiteRelativeURL\tMT[F]", tag_open + mt_prefix + "WebsiteRelativeURL${1}" + tag_close),
            (mt_prefix + "WebsiteThemeID\tMT[F]", tag_open + mt_prefix + "WebsiteThemeID${1}" + tag_close),
            (mt_prefix + "WebsiteTimezone\tMT[F]", tag_open + mt_prefix + "WebsiteTimezone${1}" + tag_close),
            (mt_prefix + "WebsiteURL\tMT[F]", tag_open + mt_prefix + "WebsiteURL${1}" + tag_close),
            (mt_prefix + "WidgetManager\tMT[F]", tag_open + mt_prefix + "WidgetManager${1}" + tag_close),
            (mt_prefix + "WidgetSet\tMT[F]", tag_open + mt_prefix + "WidgetSet${1}" + tag_close),
            (mt_prefix + "XMLRPCScript\tMT[F]", tag_open + mt_prefix + "XMLRPCScript${1}" + tag_close),
            ("mtapp:ActionBar\tMT[F]", tag_open + "mtapp:ActionBar${1}" + tag_close),
            ("mtapp:Link\tMT[F]", tag_open + "mtapp:Link${1}" + tag_close),
            ("mtapp:ListFilters\tMT[F]", tag_open + "mtapp:ListFilters${1}" + tag_close),
            ("mtapp:PageActions\tMT[F]", tag_open + "mtapp:PageActions${1}" + tag_close),
            ("mtml\tDynamicMTML[F]", tag_open + "mtml tag='${1:/}mt:${2:TagName}'${3: params=''}" + tag_close)
        ], sublime.INHIBIT_WORD_COMPLETIONS | sublime.INHIBIT_EXPLICIT_COMPLETIONS)
